### ISSUE TITLE
babel-loader@9.2.0 resulted in a runtime error

### ISSUE THREAD

**Issue by ijlee2** [babel/babel-loader#1043]
## **BEFORE YOU SUBMIT** please read the following:

*Delete what isn't applicable below*
**I'm submitting a bug report**

**Please tell us about your environment:**
Webpack Version: 5.94.0
Babel Core Version: 7.25.2
Babel Loader Version: 9.2.0

**Current behavior:**

The `start` and `test` commands for a fresh Ember app failed with a runtime error:

```sh
Module build failed (from ../../../../node_modules/.pnpm/thread-loader@3.0.4_webpack@5.94.0/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
this.getLogger is not a function
    at PoolWorker.fromErrorObj (/node_modules/.pnpm/thread-loader@3.0.4_webpack@5.94.0/node_modules/thread-loader/dist/WorkerPool.js:346:12)
    at /node_modules/.pnpm/thread-loader@3.0.4_webpack@5.94.0/node_modules/thread-loader/dist/WorkerPool.js:219:29
    at mapSeries (/node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:3625:14)
    at Object.loader (/node_modules/.pnpm/babel-loader@9.2.0_@babel+core@7.25.2_webpack@5.94.0/node_modules/babel-loader/lib/index.js:44:23)
    at Object.<anonymous> (/node_modules/.pnpm/babel-loader@9.2.0_@babel+core@7.25.2_webpack@5.94.0/node_modules/babel-loader/lib/index.js:39:12)
```

The Ember app indirectly uses [`@embroider/babel-loader-9`, which depends on `babel-loader>=9.0.0`](https://github.com/embroider-build/embroider/blob/v3.1.1-babel-loader-9/packages/babel-loader-9/index.js#L2).

**Expected/desired behavior:**

The `start` and `test` commands run without an error.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

```sh
# Create a monorepo with `docs-app` (the Ember app in question)
npx create-v2-addon-repo@0.10.4 my-repo
pnpm install

# Run `docs-app`
cd docs-app
pnpm start

# Test `docs-app`
pnpm test
```

1. Verify that `start` and `test` commands run without error.
2. Remove `pnpm.overrides` in the workspace root `package.json`. Run the `start` and `test` commands again to see the error.

**Comment by ijlee2** [comment]
I noticed that `this.getLogger()` is mentioned in https://github.com/babel/babel-loader/pull/1037/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R56. I don't know how this could have affected `@embroider/babel-loader-9`.

**Comment by nicolo-ribaudo** [comment]
Thanks for the report! I'm taking a look.

**Comment by adamsr123** [comment]
@nicolo-ribaudo it's also happening for 8.4.0

**Comment by JackHull** [comment]
Also experiencing this issue for ^8.0.4.

**Comment by anndro** [comment]
Same issue on 8.4.0 as mentioned. Rollback to 8.3.0 fixed for now.

**Comment by JackHull** [comment]
Rollback to 8.0.4 worked for me too.

**Comment by nicolo-ribaudo** [comment]
I published v8.4.1 and v9.2.1 with a workaround for this.

**Comment by ijlee2** [comment]
@nicolo-ribaudo Thank you for your help. I confirmed that, with `9.2.1`, I can run the `start` and `test` commands in a new project as well as an existing one.

**Comment by JLHwung** [comment]
I think this is a thread-loader issue, because it only provides a subset of methods available in webpack 5 loader context:

https://github.com/webpack-contrib/thread-loader/blob/b1affb4762aff199af109d4717f9ee7adf54a16a/src/index.js#L13-L75

I assumed the motivation here is to minimize the process communication overhead between the main and the worker, but it is better be fixed on the thread-loader side.

**Comment by JLHwung** [comment]
Link to the thread-loader issue: https://github.com/webpack-contrib/thread-loader/issues/185
