### ISSUE TITLE
Something wrong in my app

### ISSUE THREAD

**Issue by WenXuanYuan** [babel/babel-loader#144]
when I try to run my application an error occurred like this : 
ERROR in ./src/App.js
Module build failed: ReferenceError: [BABEL] /Users/www/Documents/pppp/src/App.js: Unknown option: base.optional
    at Logger.error (/Users/www/Documents/pppp/node_modules/babel-core/lib/transformation/file/logger.js:43:11)
    at OptionManager.mergeOptions (/Users/www/Documents/pppp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:18)
    at OptionManager.init (/Users/www/Documents/pppp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:396:10)
    at File.initOptions (/Users/www/Documents/pppp/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/Users/www/Documents/pppp/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/Users/www/Documents/pppp/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/Users/www/Documents/pppp/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/www/Documents/pppp/node_modules/babel-loader/index.js:69:12)
 @ multi app

Would you give me  some help ! thank you .

**Comment by ayhankuru** [comment]
#132

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
