### ISSUE TITLE
presets is unknown options with webpack

### ISSUE THREAD

**Issue by brickyang** [babel/babel-loader#154]
I updated babel 6.1 and when using webpack it throws an unknown options error of `.presets`

my `.babelrc` is:

```
{
  "presets": [
    "es2015",
    "react"
  ]
}
```

and webpack config file:

```
module: {
		loaders: [{
			test: /\.jsx?$/,
			loader: 'babel',
                        query: {
				presets: ['react', 'es2015']
			},
			exclude: /node_modules/,
		}, {
			test: /\.jsx?$/,
			loader: 'react-hot',
			exclude: /node_modules/
		}]
	}
```

the error message:

```
ERROR in ./src/client/entry.js
Module build failed: ReferenceError: [BABEL] /Users/brick/Dropbox/learncoding/node.js/isomorphic/src/client/entry.js: Unknown option: direct.presets
    at Logger.error (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.init (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:216:10)
    at File.initOptions (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/brick/Dropbox/learncoding/node.js/isomorphic/node_modules/babel-loader/index.js:69:12)
 @ multi main
```

I'm using 
Babel 6.1.18, 
babel-cli 6.1.4, 
babel-core 5.8.34, 
babel-loader 5.3.3, 
babel-preset-es2015 6.1.18,
 babel-preset-react-6.1.18

**Comment by losogudok** [comment]
You can try to move your babel config to webpack. It works for me.

**Comment by brickyang** [comment]
@losogudok I tried. Added query property in webpack config. Also throw an error about unknown property of query

**Comment by scriptjs** [comment]
You need to include your presets in a query or params for the loader as stated in the api for the loader.

**Comment by brickyang** [comment]
@scriptjs As I said above, I already done all what you said and nothing changed. I updated the post to provide exact information.
