### ISSUE TITLE
ES6 default parameter value

### ISSUE THREAD

**Issue by gabrielrtakeda** [babel/babel-loader#177]
Hello guys, today i figured out something weird...
I'm trying to use `babel-loader` to polyfill some ES6 code on Angular project with Webpack but, when i use version 6.2.0 it throws this error:

```
ERROR in ./app/index.js
Module build failed: Error: StringMap expected string key
    at stringmap.set (...node_modules/ng-annotate-loader/node_modules/ng-annotate/node_modules/stringmap/stringmap.js:99:19)
    at Scope.add (...node_modules/ng-annotate-loader/node_modules/ng-annotate/build/es5/scope.js:102:17)
    at ...node_modules/ng-annotate-loader/node_modules/ng-annotate/build/es5/scopetools.js:65:25
    at Array.forEach (native)
    at createScopes (...node_modules/ng-annotate-loader/node_modules/ng-annotate/build/es5/scopetools.js:64:21)
    at visit (...node_modules/ng-annotate-loader/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:25:19)
    at visit (...node_modules/ng-annotate-loader/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:43:25)
    at traverse (...node_modules/ng-annotate-loader/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:56:5)
    at Object.setupScopeAndReferences (...node_modules/ng-annotate-loader/node_modules/ng-annotate/build/es5/scopetools.js:18:5)
    at ngAnnotate (...node_modules/ng-annotate-loader/node_modules/ng-annotate/build/es5/ng-annotate-main.js:1055:16)
 @ ./app/core/bootstrap.js 8:16-35
```

This error occurs with following `webpack.config.js` configurations:
```json
"devDependencies": {
  "babel-core": "^6.3.17",
  "babel-loader": "^6.2.0",
  "css-loader": "^0.23.0",
  "jshint": "^2.8.0",
  "jshint-loader": "^0.8.3",
  "ng-annotate-loader": "0.0.10",
  "node-sass": "^3.4.2",
  "sass-loader": "^3.1.2",
  "style-loader": "^0.13.0",
  "webpack": "^1.12.9",
  "webpack-dev-server": "^1.14.0"
},
  "dependencies": {
  "angular": "^1.4.8"
}
```

When i use configurations below its ok:
```json
"devDependencies": {
  "babel-core": "^6.3.17",
  "babel-loader": "^5.3.1",
  "css-loader": "^0.23.0",
  "jshint": "^2.8.0",
  "jshint-loader": "^0.8.3",
  "ng-annotate-loader": "0.0.10",
  "node-sass": "^3.4.2",
  "sass-loader": "^3.1.2",
  "style-loader": "^0.13.0",
  "webpack": "^1.12.9",
  "webpack-dev-server": "^1.14.0"
},
  "dependencies": {
  "angular": "^1.4.8"
}
```

This is the code I trying to polyfill:
```javascript
'use strict';

module.exports = angular.module('app', []);

function printMessage (status='working') {
  let message = 'ES6';
  console.log(`${message} is ${status}`);
}
printMessage();
```

I just thought I'd better warn them about this error for future improvements.
And sorry for bad English.
Best regards

**Comment by Xiphe** [comment]
:+1:

**Comment by Couto** [comment]
`npm install babel-react-es2015 -D`

and add the `preset: ['es2015']` option :)
