### ISSUE TITLE
export wildcard, ts-loader and sourcemaps error

### ISSUE THREAD

**Issue by Strate** [babel/babel-loader#188]
Hi! I am using babel-loader in combination with ts-loader:

```
loaders: [
  "babel?presets[]=react,presets[]=es2015",
  "ts",
],
```

`ts-laoder` always emits sourceMaps. It works pretty well, but fails in case, when I am trying to use reexport with a wildcard:

```
export * from "./file"
```

It fails with:

```
ERROR in ./src/lib/entities/index.ts
Module build failed: TypeError: /home/www/project/src/lib/entities/index.ts: Cannot read property 'indexOf' of undefined
    at Object.relative (/home/www/project/node_modules/source-map/lib/util.js:206:17)
    at SourceMapConsumer_generatedPositionFor [as generatedPositionFor] (/home/www/project/node_modules/source-map/lib/source-map-consumer.js:730:23)
    at /home/www/project/node_modules/babel-core/lib/transformation/file/index.js:445:53
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/home/www/project/node_modules/source-map/lib/source-map-consumer.js:155:16)
    at /home/www/project/node_modules/babel-core/lib/transformation/file/index.js:444:26
    at File.mergeSourceMap (/home/www/project/node_modules/babel-core/lib/transformation/file/index.js:469:9)
    at File.generate (/home/www/project/node_modules/babel-core/lib/transformation/file/index.js:663:25)
    at File.transform (/home/www/project/node_modules/babel-core/lib/transformation/file/index.js:510:17)
    at /home/www/project/node_modules/babel-core/lib/transformation/pipeline.js:46:19
    at File.wrap (/home/www/project/node_modules/babel-core/lib/transformation/file/index.js:520:16)
    at Pipeline.transform (/home/www/project/node_modules/babel-core/lib/transformation/pipeline.js:43:17)
    at transpile (/home/www/project/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/home/www/project/node_modules/babel-loader/index.js:87:14)
```

Is it targeted to babel-loader?

**Comment by arantir** [comment]
It's not a wildcard, it's rather a file with no other lines than module imports (no _actual_ code).
babel-core does not expect that a file may have no sources and source maps at all https://github.com/babel/babel/blob/8b55f4dfc252f812b276669ce1be0e2a4922ee11/packages/babel-core/src/transformation/file/index.js#L365

It's either TypeScript bug with source maps of "empty" files, or Babel bug with reading such source maps (I don't know source maps specification to say who is right).

**Comment by Strate** [comment]
But `export {one, two, three} from "./file"` works perfectly.
And yet another note: typescript compiles to es6, if it has a sense.

**Comment by arantir** [comment]
Welcome to fancy world of source mapping.

Shortly:
If you do `export * from "./file"` webpack produces a bit of mess and no lines can be directly mapped.
If you do `export {one, two, three} from "./file"` there are a few lines mapped to those variables.

Example output:
```js
Object.defineProperty(exports, "one", {
  enumerable: true,
  get: function get() {
    return _browser.one;
  }
});
```
Mapping: `return _browser.one;` → `one`

To be fair, imports should be mapped as well:
`var _file = __webpack_require__(1);` → `import "./file"`

**Comment by Toilal** [comment]
I can reproduce this issue too. I'm using typescript (2.2.2) with `"target": "es6"` in `tsconfig.json`, and then it goes through babel to transpile to es5. 

It gives this Stacktrace

```
Module build failed: TypeError: /home/toilal/idea-projects/vue-test/src/hooks.ts: Cannot read property 'indexOf' of undefined
    at Object.relative (/home/toilal/idea-projects/vue-test/node_modules/source-map/lib/util.js:206:15)
    at SourceMapConsumer_generatedPositionFor [as generatedPositionFor] (/home/toilal/idea-projects/vue-test/node_modules/source-map/lib/source-map-consumer.js:731:21)
    at /home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/file/index.js:461:51
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/home/toilal/idea-projects/vue-test/node_modules/source-map/lib/source-map-consumer.js:155:14)
    at File.mergeSourceMap (/home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/file/index.js:460:24)
    at File.generate (/home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/file/index.js:719:25)
    at File.transform (/home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/file/index.js:554:17)
    at /home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/pipeline.js:50:19
    at File.wrap (/home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/file/index.js:564:16)
    at Pipeline.transform (/home/toilal/idea-projects/vue-test/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at transpile (/home/toilal/idea-projects/vue-test/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/home/toilal/idea-projects/vue-test/node_modules/babel-loader/lib/index.js:163:20)
```

The problems only occurs when a file containing comments only (`src/hooks.ts`) is imported. This module doesn't have any export.

My current workaround is to add an undefined default export in the empty `src/hooks.ts` file.

```
export default undefined
```

**Comment by loganfsmyth** [comment]
I believe this should be resolved in Babel 7. Feel free to open a new issue if there is still a problem.
