### ISSUE TITLE
Node mysql with webpack(1.0.0) results in an error

### ISSUE THREAD

**Issue by opensourcegeek** [babel/babel-loader#211]
I get this error 

` 70% 103/103 build modules/home/opensourcegeek/projects/test-node-webpack/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:42
	var i = req.indexOf("?");
	            ^

TypeError: req.indexOf is not a function
    at DependenciesBlock.splitQuery (/home/opensourcegeek/projects/test-node-webpack/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:42:14)
    at DependenciesBlock.NormalModuleMixin (/home/opensourcegeek/projects/test-node-webpack/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:25:26)
    at DependenciesBlock.NormalModule (/home/opensourcegeek/projects/test-node-webpack/node_modules/webpack/lib/NormalModule.js:21:20)
    at /home/opensourcegeek/projects/test-node-webpack/node_modules/webpack/lib/NormalModuleFactory.js:96:7
    at Tapable.applyPluginsAsyncWaterfall (/home/opensourcegeek/projects/test-node-webpack/node_modules/webpack/node_modules/tapable/lib/Tapable.js:75:69)
    at Tapable.onDoneResolving (/home/opensourcegeek/projects/test-node-webpack/node_modules/webpack/lib/NormalModuleFactory.js:82:10)
    at Tapable.<anonymous> (/home/opensourcegeek/projects/test-node-webpack/node_modules/webpack/lib/NormalModuleFactory.js:78:22)
    at /home/opensourcegeek/projects/test-node-webpack/node_modules/webpack/node_modules/async/lib/async.js:232:13
    at /home/opensourcegeek/projects/test-node-webpack/node_modules/webpack/node_modules/async/lib/async.js:119:25
    at /home/opensourcegeek/projects/test-node-webpack/node_modules/webpack/node_modules/async/lib/async.js:24:16
`

This happens only when I import [mysql](https://github.com/felixge/node-mysql) library. That mysql library seem to have dynamic requires embedded in switch case statements not sure if that's an issue. It seems like "req" variable is set to false when it gets passed to that splitQuery function. Any hints?

**Comment by loganfsmyth** [comment]
It doesn't seem like this has anything to do with `babel-loader`. Perhaps swing by Wehbpack's support channel? https://gitter.im/webpack/webpack

**Comment by opensourcegeek** [comment]
Will do - thanks
