### ISSUE TITLE
Using removed Babel 5 option: base.optional

### ISSUE THREAD

**Issue by alexcheninfo** [babel/babel-loader#228]
Full error:

> ERROR in ./~/babel-loader?optional[]=runtime&loose=all&nonStandard=false!./~/vue-loader/lib/selector.js?type=script&index=0!./app/components/Preference.vue
> Module build failed: ReferenceError: [BABEL] /home/alex/node/~iCultus/iCultus/app/components/Preference.vue: Using removed Babel 5 option: base.optional - Put the specific transforms you want in the `plugins` option

You get this error when you try to do `npm run release` in this project: https://github.com/djyde/iCultus

This is the conflicting file:

https://github.com/djyde/iCultus/blob/master/app/components/Preference.vue

I couldn't find anything that said `base.option`. What specific thing is `babel-loader` referring to?

Note: I installed `babel-preset-es2015@6.6.0` and created a .babelrc file with `"presents": ["e2015"]`. Not sure if this is the cause of the problem (conflicting versions between babel 5 and 6).

**Comment by raz21** [comment]
Getting similar error for my app

ERROR in ./index.android.js
Module build failed: ReferenceError: [BABEL] ~\index.android.js: 
Using removed Babel 5 option: base.optional - Put the specific transforms you want in the plugins` option
    at Logger.error (D:\MyReakt\TelMed\node_modules\babel-core\lib\transformation\file\logger.js:43:11)
    at OptionManager.mergeOptions (~\node_modules\babel-core\lib\transformation\file\options\option-manager.js:305:20)
    at OptionManager.init (~\node_modules\babel-core\lib\transformation\file\options\option-manager.js:506:10)
    at File.initOptions (~\node_modules\babel-core\lib\transformation\file\index.js:243:89)
    at new File (~\node_modules\babel-core\lib\transformation\file\index.js:159:72)
    at Pipeline.transform (~\node_modules\babel-core\lib\transformation\pipeline.js:49:16)
    at transpile (~\node_modules\babel-loader\index.js:14:22)
    at Object.module.exports (~\node_modules\babel-loader\index.js:88:12)
 @ multi main

**Comment by maheshambiga** [comment]
facing similar issue.

**Comment by JomaKar** [comment]
one more with the problem:

ERROR in ./src/app.jsx
Module build failed: ReferenceError: [BABEL] /Users/xxx/De/src/app.jsx: Using removed Babel 5 option: base.optional - Put the specific transforms you want in the `plugins` option
    at Logger.error (/Users/xxxxx/Desktop/school/Platzi/React/tutsTuto/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/xxeact/tutsTuto/node_modules/babel-core/lib/transformation/file/options/option-manager.js:233:20)
    at OptionManager.init (/Users/xxx/React/tutsTuto/node_modules/babel-core/lib/transformation/file/options/option-manager.js:360:12)
    at File.initOptions (/Users/xxx/DesktoReact/tutsTuto/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/school/Platzi/React/tutsTuto/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/Usersxxxxi/React/xxxx/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/xxxx/Platzi/React/tutsTuto/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/xxxx/Platzi/React/tutsTuto/node_modules/babel-loader/index.js:88:12)
 @ multi main

**Comment by asciiman** [comment]
I found a "whitelist" in my .babelrc file.

```

  "presets": ["es2015" , "stage-0", "react"],
  "plugins": ["transform-runtime"],
  "whitelist": ["es6.modules"],
  "retainLines": true,
  "compact": true,
  "comments": false,
  "sourceMaps": false
}
```

When I remove it the error goes away.  I'm not sure where to put "es6.modules" though.

**Comment by BobLamarley** [comment]
Same problem for me 
`ERROR in ./src/client/index.js
Module build failed: ReferenceError: [BABEL] C:\Users\tom\Desktop\npmcheck\src\client\index.js: Using removed Babel 5 option: base.optional - Put the specific transforms you want in the `plugins` option
    at Logger.error (C:\Users\tom\Desktop\npmcheck\node_modules\babel-core\lib\transformation\file\logger.js:41:11)
    at OptionManager.mergeOptions (C:\Users\tom\Desktop\npmcheck\node_modules\babel-core\lib\transformation\file\options\option-manager.js:233:20)
    at OptionManager.init (C:\Users\tom\Desktop\npmcheck\node_modules\babel-core\lib\transformation\file\options\option-manager.js:383:12)
    at File.initOptions (C:\Users\tom\Desktop\npmcheck\node_modules\babel-core\lib\transformation\file\index.js:223:65)
    at new File (C:\Users\tom\Desktop\npmcheck\node_modules\babel-core\lib\transformation\file\index.js:140:24)
    at Pipeline.transform (C:\Users\tom\Desktop\npmcheck\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\tom\Desktop\npmcheck\node_modules\babel-loader\index.js:14:22)
    at Object.module.exports (C:\Users\tom\Desktop\npmcheck\node_modules\babel-loader\index.js:88:12)`

And i have a .babelrc file which contains 
`{
    
  "plugins": ["transform-object-rest-spread"],
  "presets": [
    "react",
    "es2015"
  ]
}
`

And in my webpack.confing.js, i have this 
`
  webpackConfig = merge(webpackConfig,{
    devtool: "source-map",
    entry : [
      './src/client/index.js'
    ],
    module: {
      loaders: [{
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        include: __dirname
      },
      { test: /\.(png|jpg|gif|jpeg)$/, loader: 'url-loader?limit=8192'},
      { test: /\.css$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader?sourceMap') }
    ]},
    plugins : [
      new webpack.DefinePlugin({
        'process.env': {
          NODE_ENV: JSON.stringify('production')
        }
      }),
      new ExtractTextPlugin("app.css"),
      new webpack.optimize.UglifyJsPlugin({minimize: true})
    ]  
  });`

If someone have a fix for this problem, it would be helpful
Have a good day :)

**Comment by dutch92** [comment]
npm install --save-dev babel-plugin-transform-runtime
npm install --save babel-runtime

part of my webpack.config,js
```
module: {
        loaders: [{
            test: /\.js$/,
            exclude: /(node_modules|bower_components)/,
            loader: 'babel',
            query: {
                presets: ['es2015'],
                plugins: ['transform-runtime']
            }
        }]
    }
```

**Comment by danez** [comment]
Ensure you are using the latest version of babel-loader and babel-core.

**Comment by loganfsmyth** [comment]
Do you happen to have a somewhere else config might be, like a `.babelrc` or in your webpack config? The snippet you posted seems alright to me.

**Comment by NajiJzr** [comment]
There is this code inside webpack config : 
```
        module: {
            loaders: [
                { test: /\.jsx$/, exclude: /node_modules/, loader: 'babel-loader'}
            ]
        },
        devtool: 'source-map',
        plugins: [
            new CommonsChunkPlugin('../core.min.js', undefined, 2),
            new UglifyJsPlugin({ compress: { warnings: false } })
        ]
```

**Comment by loganfsmyth** [comment]
Are you sure there isn't anything else? The `base.modules` in that message strongly implies that there are arguments being passed to `babel-loader` somewhere. Maybe it would help if you posted the full error message with stacktrace?

**Comment by NajiJzr** [comment]
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
ReferenceError: [BABEL] /home/me/myProject/src/account.js: Using removed Babel 5 option: base.modules - Use the corresponding module transform plugin in the `plugins` option. Check out http://babeljs.io/docs/plugins/#modules
a    at OptionManager.mergeOptions (/home/me/myProject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:220:20)
    at OptionManager.init (/home/me/myProject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/me/myProject/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/me/myProject/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/me/myProject/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at DestroyableTransform._transform (/home/me/myProject/node_modules/gulp-babel/index.js:36:22)
    at DestroyableTransform.Transform._read (/home/me/myProject/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/me/myProject/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/home/me/myProject/node_modules/readable-stream/lib/_stream_writable.js:418:64)
    at writeOrBuffer (/home/me/myProject/node_modules/readable-stream/lib/_stream_writable.js:407:5)
    at DestroyableTransform.Writable.write (/home/me/myProject/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/home/me/myProject/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at addChunk (/home/me/myProject/node_modules/readable-stream/lib/_stream_readable.js:291:12)
```

Note that when I use Plumber this error hits all js files in my src folder. Any idea ?

**Comment by loganfsmyth** [comment]
Whereever you are calling `gulp-babel` you are passing it incorrect options.

**Comment by NajiJzr** [comment]
You're right :smiley: , modules was called somewhere else and I fixed the problem now.
But I got another error, note that my project is an Aurelia project : 
```
    events.js:160
          throw er; // Unhandled 'error' event
          ^
    SyntaxError: /home/me/myProject/src/account.js: Unexpected token (9:0)
       7 | import {SimpleDialog} from 'lib/simple-dialog';
       8 | 
    >  9 | @inject(AuthService, Router, PivotClient, SimpleDialog)
         | ^
      10 | export class Account{
      11 | 
      12 |   userContext;
        at Parser.pp$5.raise (/home/me/myProject/node_modules/babel-core/node_modules/babylon/lib/index.js:4454:13)
        at Parser.pp.unexpected (/home/me/myProject/node_modules/babel-core/node_modules/babylon/lib/index.js:1761:8)
        at Parser.pp$1.parseDecorator (/home/me/myProject/node_modules/babel-core/node_modules/babylon/lib/index.js:1939:10)
        at Parser.pp$1.parseDecorators (/home/me/myProject/node_modules/babel-core/node_modules/babylon/lib/index.js:1924:26)
        at Parser.pp$1.parseStatement (/home/me/myProject/node_modules/babel-core/node_modules/babylon/lib/index.js:1818:10)
        at Parser.pp$1.parseBlockBody (/home/me/myProject/node_modules/babel-core/node_modules/babylon/lib/index.js:2268:21)
        at Parser.pp$1.parseTopLevel (/home/me/myProject/node_modules/babel-core/node_modules/babylon/lib/index.js:1778:8)
        at Parser.parse (/home/me/myProject/node_modules/babel-core/node_modules/babylon/lib/index.js:1673:17)
        at parse (/home/me/myProject/node_modules/babel-core/node_modules/babylon/lib/index.js:7305:37)
        at File.parse (/home/me/myProject/node_modules/babel-core/lib/transformation/file/index.js:517:15)
        at File.parseCode (/home/me/myProject/node_modules/babel-core/lib/transformation/file/index.js:602:20)
        at /home/me/myProject/node_modules/babel-core/lib/transformation/pipeline.js:49:12
        at File.wrap (/home/me/myProject/node_modules/babel-core/lib/transformation/file/index.js:564:16)
        at Pipeline.transform (/home/me/myProject/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
        at DestroyableTransform._transform (/home/me/myProject/node_modules/gulp-babel/index.js:36:22)
        at DestroyableTransform.Transform._read (/home/me/myProject/node_modules/readable-stream/lib/_stream_transform.js:184:10)

```

Before updating node version from v0.12.18 to v6.9.1 I was having this babel options : 
```
  presets: [
    ["es2015", {
      loose: true,
      modules: false
    }]
  ],
  moduleIds: false,
  comments: false,
  compact: false,
  // stage:2,
  // optional: [
  //   "es7.decorators",
  //   "es7.classProperties"
  // ]
```
the commented options when they are present they produce Babel error : `Using removed Babel 5 option: base.optional` & `Using removed Babel 5 option: base.stage`. 

But I think they are the ones whom was responsible to make the syntax of Aurelia valid ( @inject  & other syntax). So my question : do you know how to support them correctly with modern versions ?

**Comment by loganfsmyth** [comment]
You'll want to use `babel-preset-stage-2` and `babel-plugin-transform-decorators-legacy`, so install those two and do
```
  presets: [
    ["es2015", {
      loose: true,
      modules: false
    }],
    "stage-2",
  ],
  plugins: [
    "transform-decorators-legacy"
  ],
```

**Comment by NajiJzr** [comment]
Thanks a lot man :smiley: , it worked.

**Comment by egiacalone** [comment]
Grazie

**Comment by jasonfb** [comment]
this happened to me after I inadvertently added `stage: 1` to my `server/.babelrc` file. 
```
{
  "presets": ["es2015", "stage-0"],
  "plugins": ["transform-runtime"],
   stage: 1
}
```

fixed by removing this

```
{
  "presets": ["es2015", "stage-0"],
  "plugins": ["transform-runtime"],
}
```

**Comment by jacqui126** [comment]
Couldn't find preset "module:metro-react-native-babel-preset"

When i put  `.babelrc` 
{
  "presets": ["module:metro-react-native-babel-preset"]
}
`npm i babel-preset-react-native --save-dev`
to 
{
  "presets": ["react-native"]

Appear like this problem

Module build failed: ReferenceError: Using removed Babel 5 option: .stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at throwUnknownError (E:\amanpuri-mobile\node_modules\@babel\core\lib\config\validation\options.js:120:11)
    at Object.keys.forEach.key (E:\amanpuri-mobile\node_modules\@babel\core\lib\config\validation\options.js:107:5)
    at Array.forEach (<anonymous>)
}
