### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by zjtws** [babel/babel-loader#230]
**package.json:**
{
  "name": "import",
  "version": "1.3.1",
  "dependencies": {
    "babel-plugin-transform-runtime": "^6.6.0",
    "check-types": "^4.3.0",
    "classnames": "^2.1.3",
    "es6-promise": "^3.0.2",
    "exports-loader": "^0.6.2",
    "history": "^1.13.1",
    "imports-loader": "^0.6.5",
    "jsonp": "^0.2.0",
    "rc-progress": "^1.0.4",
    "react": "^0.14.2",
    "react-dom": "^0.14.2",
    "react-router": "^1.0.0",
    "react-tappable": "^0.7.1",
    "superagent": "^1.4.0",
    "superagent-promise": "^1.0.3"
  },
  "devDependencies": {
    "autoprefixer": "^6.0.3",
    "autoprefixer-loader": "*",
    "babel-core": "^6.7.4",
    "babel-eslint": "^4.1.3",
    "babel-loader": "*",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "clone": "*",
    "css-loader": "*",
    "cssnext": "^1.8.4",
    "eslint": "^1.5.1",
    "eslint-config-airbnb": "0.0.8",
    "eslint-loader": "^1.0.0",
    "extract-text-webpack-plugin": "^0.8.2",
    "file-loader": "*",
    "postcss-calc": "^5.0.0",
    "postcss-loader": "^0.6.0",
    "precss": "^1.1.3",
    "react": "^0.14.2",
    "react-addons-transition-group": "^0.14.2",
    "react-dom": "^0.14.0",
    "react-hot-loader": "*",
    "react-tools": "*",
    "source-map-loader": "*",
    "style-loader": "*",
    "webpack": "^1.12.2",
    "webpack-dev-server": "*"
  },
  "scripts": {
    "build": "rm -rf build && webpack -p --config ./config/webpack.config.js",
    "dev": "NODE_ENV=dev webpack-dev-server --host 0.0.0.0 --colors --content-base ./build --config ./config/webpack.dev.config.js",
    "serve": "node hot-server.js"
  },
  "author": "",
  "license": "MIT"
}

**webpack.config.js**
  module: {
        loaders: [
            {
                test: /\.(js)?$/,
                loaders: [
                    'react-hot',
                    'babel?stage=0,presets[]=react,presets[]=es2015'
                ],
                exclude: /node_modules/
            },
            {
                test: /\.(css)$/,
                loader: ExtractTextPlugin.extract(
                    'style-loader',
                    'css-loader!postcss-loader', {
                        publicPath: '../'
                    }
                ),
                exclude: /node_modules/
            },
            {
                test: /\.(html)$/,
                exclude: /node_modules/,
                loader: 'file?name=[path][name].[ext]&context=./src'
            },
            {
                test: /.*\.(gif|png|jpe?g|svg)$/i,
                exclude: /node_modules/,
                loaders: [
                  'file?hash=sha512&digest=hex&name=[path][hash].[ext]&context=./src'
                ]
            }
        ]
    },

**Command:**
 sudo npm run build

**Error:**
ERROR in ./src/scripts/pg.js
Module build failed: ReferenceError: [BABEL] /Users/taoweisong/Desktop/import.git/src/scripts/pg.js: Using removed Babel 5 option: base.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at Logger.error (/Users/taoweisong/Desktop/import.git/node_modules/babel-core/lib/transformation/file/logger.js:39:11)
    at OptionManager.mergeOptions (/Users/taoweisong/Desktop/import.git/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:20)
    at OptionManager.init (/Users/taoweisong/Desktop/import.git/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
    at File.initOptions (/Users/taoweisong/Desktop/import.git/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/Users/taoweisong/Desktop/import.git/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (/Users/taoweisong/Desktop/import.git/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at transpile (/Users/taoweisong/Desktop/import.git/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/taoweisong/Desktop/import.git/node_modules/babel-loader/index.js:88:12)

ERROR in ./src/scripts/index.js
Module build failed: ReferenceError: [BABEL] /Users/taoweisong/Desktop/import.git/src/scripts/index.js: Using removed Babel 5 option: base.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at Logger.error (/Users/taoweisong/Desktop/import.git/node_modules/babel-core/lib/transformation/file/logger.js:39:11)
    at OptionManager.mergeOptions (/Users/taoweisong/Desktop/import.git/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:20)
    at OptionManager.init (/Users/taoweisong/Desktop/import.git/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
    at File.initOptions (/Users/taoweisong/Desktop/import.git/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/Users/taoweisong/Desktop/import.git/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (/Users/taoweisong/Desktop/import.git/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at transpile (/Users/taoweisong/Desktop/import.git/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/taoweisong/Desktop/import.git/node_modules/babel-loader/index.js:88:12)
 @ multi app

**Comment by abouthiroppy** [comment]
Did you resolve the issue?
