### ISSUE TITLE
Export error for `transform-react-pure-class-to-function`

### ISSUE THREAD

**Issue by jhen0409** [babel/babel-loader#270]
I found a little problem when handling https://github.com/chentsulin/electron-react-boilerplate/issues/278, the following code will broken: (Although maybe no one will do so..)

```js
import { Component } from 'react'
export class A extends React.Component {
  render() {
    return (<div></div>)
  }
}
export default A
```

It work fine when I change `export class A` to `class A`, I can only reproduce it with `babel-loader`. (`$ babel comp.js` is work fine)

The stacktrace:

```
ERROR in ./comp.js
Module build failed: Error: /project_path/comp.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertAfter (/project_path/node_modules/babel-traverse/lib/path/modification.js:190:13)
    at NodePath.replaceWithMultiple (/project_path/node_modules/babel-traverse/lib/path/replacement.js:93:8)
    at PluginPass.Class (/project_path/node_modules/babel-plugin-transform-react-pure-class-to-function/lib/index.js:96:14)
    at newFn (/project_path/node_modules/babel-traverse/lib/visitors.js:301:19)
    at NodePath._call (/project_path/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/project_path/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/project_path/node_modules/babel-traverse/lib/path/context.js:106:12)
    at TraversalContext.visitQueue (/project_path/node_modules/babel-traverse/lib/context.js:167:16)
    at TraversalContext.visitSingle (/project_path/node_modules/babel-traverse/lib/context.js:118:19)
    at TraversalContext.visit (/project_path/node_modules/babel-traverse/lib/context.js:211:19)
    at Function.traverse.node (/project_path/node_modules/babel-traverse/lib/index.js:161:17)
    at NodePath.visit (/project_path/node_modules/babel-traverse/lib/path/context.js:116:19)
    at TraversalContext.visitQueue (/project_path/node_modules/babel-traverse/lib/context.js:167:16)
    at TraversalContext.visitMultiple (/project_path/node_modules/babel-traverse/lib/context.js:113:17)
    at TraversalContext.visit (/project_path/node_modules/babel-traverse/lib/context.js:209:19)
    at Function.traverse.node (/project_path/node_modules/babel-traverse/lib/index.js:161:17)
    at NodePath.visit (/project_path/node_modules/babel-traverse/lib/path/context.js:116:19)
    at TraversalContext.visitQueue (/project_path/node_modules/babel-traverse/lib/context.js:167:16)
    at TraversalContext.visitSingle (/project_path/node_modules/babel-traverse/lib/context.js:118:19)
    at TraversalContext.visit (/project_path/node_modules/babel-traverse/lib/context.js:211:19)
    at Function.traverse.node (/project_path/node_modules/babel-traverse/lib/index.js:161:17)
    at traverse (/project_path/node_modules/babel-traverse/lib/index.js:83:12)
    at File.transform (/project_path/node_modules/babel-core/lib/transformation/file/index.js:548:35)
    at /project_path/node_modules/babel-core/lib/transformation/pipeline.js:50:19
    at File.wrap (/project_path/node_modules/babel-core/lib/transformation/file/index.js:563:16)
    at Pipeline.transform (/project_path/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at transpile (/project_path/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/project_path/node_modules/babel-loader/index.js:88:12)
```

**Comment by gaearon** [comment]
babel-loader is only concerned with Babel <-> Webpack interaction.
If there is a bug in that plugin, please file it in the related repo: https://github.com/thejameskyle/babel-react-optimize/tree/master/packages/babel-plugin-transform-react-pure-class-to-function

Thanks!
