### ISSUE TITLE
How can I configure babel preset options with query params?

### ISSUE THREAD

**Issue by donaldpipowitch** [babel/babel-loader#286]
E.g. say I have `babel?presets[]=es2015` and I want to disable modules (see https://github.com/babel/babel/blob/master/CHANGELOG.md#preset-options-babelnotes) how can I do that? Is there an example available?

Is this the best way?

``` js
`babel?${JSON.stringify({
  presets: [
    [ 'babel-preset-es2015' , { modules: false } ]
  ]
})}`
```

**Comment by aarongodin** [comment]
There is also a "query" property on each object in loaders that will converted to JSON. Ex:

```
{
  test: /\.js$/,
  loader: 'babel',
  query: {
    presets: [
      [ 'babel-preset-es2015' , { modules: false } ]
    ]
  },
  exclude: /node_modules/
}
```

**Comment by fkrauthan** [comment]
If I have something like this in my project:
```js
{
                test: /\.jsx?$/,
                exclude: /node_modules/,
                loader: "babel",
                query: {
                    presets: [
                        "react",
                        ["es2015", { modules: false }],
                        "stage-0",
                    ],
                },
            }
```

I get the following error output:
```
ERROR in ./src/client/main.js
Module build failed: TypeError: [BABEL] /Users/fkrauthan/WebstormProjects/west-coast-sailing-club/web-ui/src/client/main.js: Invalid options type for foreign
    at Logger.error (/Users/fkrauthan/WebstormProjects/west-coast-sailing-club/web-ui/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/fkrauthan/WebstormProjects/west-coast-sailing-club/web-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:211:16)
    at /Users/fkrauthan/WebstormProjects/west-coast-sailing-club/web-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:289:14
    at /Users/fkrauthan/WebstormProjects/west-coast-sailing-club/web-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:316:22
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/fkrauthan/WebstormProjects/west-coast-sailing-club/web-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
    at OptionManager.mergePresets (/Users/fkrauthan/WebstormProjects/west-coast-sailing-club/web-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:288:10)
    at OptionManager.mergeOptions (/Users/fkrauthan/WebstormProjects/west-coast-sailing-club/web-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:14)
    at OptionManager.init (/Users/fkrauthan/WebstormProjects/west-coast-sailing-club/web-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:360:12)
    at File.initOptions (/Users/fkrauthan/WebstormProjects/west-coast-sailing-club/web-ui/node_modules/babel-core/lib/transformation/file/index.js:223:65)
 @ multi app
```

If I replace `["es2015", { modules: false }],` with `"es2015",` everything is working fine. Any idea what I need to change?

**Comment by aarongodin** [comment]
@fkrauthan Which version of babel are you using? Plugin options are only supported as of [6.13.0](https://github.com/babel/babel/blob/master/CHANGELOG.md#v6130-2016-08-04).

If that's not the issue, there might be something between any of the presets included from stage-0 and es2015 that are conflicting. Is there anything you absolutely need from stage-0? It's fairly dangerous for production applications.

**Comment by fkrauthan** [comment]
Here the output of my babel dependencies:
```
fkrauthan$ npm list | grep babel
+-- babel-cli@6.11.4
| +-- babel-core@6.13.2
| | +-- babel-code-frame@6.11.0
| | +-- babel-generator@6.11.4
| | +-- babel-helpers@6.8.0
| | +-- babel-messages@6.8.0
| | +-- babel-template@6.9.0
| +-- babel-runtime@6.11.6
+-- babel-eslint@6.1.2
| +-- babel-traverse@6.13.0
| +-- babel-types@6.13.0
+-- babel-loader@6.2.5
+-- babel-plugin-react-transform@2.0.2
+-- babel-polyfill@6.13.0
+-- babel-preset-es2015@6.13.2
| +-- babel-plugin-check-es2015-constants@6.8.0
| +-- babel-plugin-transform-es2015-arrow-functions@6.8.0
| +-- babel-plugin-transform-es2015-block-scoped-functions@6.8.0
| +-- babel-plugin-transform-es2015-block-scoping@6.10.1
| +-- babel-plugin-transform-es2015-classes@6.9.0
| | +-- babel-helper-define-map@6.9.0
| | +-- babel-helper-function-name@6.8.0
| | +-- babel-helper-optimise-call-expression@6.8.0
| | `-- babel-helper-replace-supers@6.8.0
| +-- babel-plugin-transform-es2015-computed-properties@6.8.0
| +-- babel-plugin-transform-es2015-destructuring@6.9.0
| +-- babel-plugin-transform-es2015-duplicate-keys@6.8.0
| +-- babel-plugin-transform-es2015-for-of@6.8.0
| +-- babel-plugin-transform-es2015-function-name@6.9.0
| +-- babel-plugin-transform-es2015-literals@6.8.0
| +-- babel-plugin-transform-es2015-modules-amd@6.8.0
| +-- babel-plugin-transform-es2015-modules-commonjs@6.11.5
| | `-- babel-plugin-transform-strict-mode@6.11.3
| +-- babel-plugin-transform-es2015-modules-systemjs@6.12.0
| | `-- babel-helper-hoist-variables@6.8.0
| +-- babel-plugin-transform-es2015-modules-umd@6.12.0
| +-- babel-plugin-transform-es2015-object-super@6.8.0
| +-- babel-plugin-transform-es2015-parameters@6.11.4
| | +-- babel-helper-call-delegate@6.8.0
| | `-- babel-helper-get-function-arity@6.8.0
| +-- babel-plugin-transform-es2015-shorthand-properties@6.8.0
| +-- babel-plugin-transform-es2015-spread@6.8.0
| +-- babel-plugin-transform-es2015-sticky-regex@6.8.0
| | `-- babel-helper-regex@6.9.0
| +-- babel-plugin-transform-es2015-template-literals@6.8.0
| +-- babel-plugin-transform-es2015-typeof-symbol@6.8.0
| +-- babel-plugin-transform-es2015-unicode-regex@6.11.0
| `-- babel-plugin-transform-regenerator@6.11.4
|   `-- babel-plugin-syntax-async-functions@6.13.0
+-- babel-preset-react@6.11.1
| +-- babel-plugin-syntax-flow@6.13.0
| +-- babel-plugin-syntax-jsx@6.13.0
| +-- babel-plugin-transform-flow-strip-types@6.8.0
| +-- babel-plugin-transform-react-display-name@6.8.0
| +-- babel-plugin-transform-react-jsx@6.8.0
| | `-- babel-helper-builder-react-jsx@6.9.0
| +-- babel-plugin-transform-react-jsx-self@6.11.0
| `-- babel-plugin-transform-react-jsx-source@6.9.0
+-- babel-preset-stage-0@6.5.0
| +-- babel-plugin-transform-do-expressions@6.8.0
| | `-- babel-plugin-syntax-do-expressions@6.13.0
| +-- babel-plugin-transform-function-bind@6.8.0
| | `-- babel-plugin-syntax-function-bind@6.13.0
| `-- babel-preset-stage-1@6.13.0
|   +-- babel-plugin-transform-class-constructor-call@6.8.0
|   | `-- babel-plugin-syntax-class-constructor-call@6.13.0
|   +-- babel-plugin-transform-export-extensions@6.8.0
|   | `-- babel-plugin-syntax-export-extensions@6.13.0
|   `-- babel-preset-stage-2@6.13.0
|     +-- babel-plugin-transform-class-properties@6.11.5
|     | `-- babel-plugin-syntax-class-properties@6.13.0
|     +-- babel-plugin-transform-decorators@6.13.0
|     | +-- babel-helper-explode-class@6.8.0
|     | | `-- babel-helper-bindify-decorators@6.8.0
|     | `-- babel-plugin-syntax-decorators@6.13.0
|     +-- babel-plugin-transform-object-rest-spread@6.8.0
|     | `-- babel-plugin-syntax-object-rest-spread@6.13.0
|     `-- babel-preset-stage-3@6.11.0
|       +-- babel-plugin-syntax-trailing-function-commas@6.13.0
|       +-- babel-plugin-transform-async-to-generator@6.8.0
|       | `-- babel-helper-remap-async-to-generator@6.11.2
|       `-- babel-plugin-transform-exponentiation-operator@6.8.0
|         +-- babel-helper-builder-binary-assignment-operator-visitor@6.8.0
|         | `-- babel-helper-explode-assignable-expression@6.8.0
|         `-- babel-plugin-syntax-exponentiation-operator@6.13.0
+-- babel-register@6.11.6
| | +-- babel-plugin-transform-runtime@6.12.0
```

**Comment by blacksonic** [comment]
here is the correct setup, look at the babel release notes

```
presets: [
  ['es2015', { loose: true, modules: false }]
]
```

**Comment by sylvesteraswin** [comment]
I am facing the exact same problem.. Did anyone figure out how to fix this.. The below is my configuration in `.babelrc`.

`{
  "presets": [[
      "env", {
          "targets": {
              "node": true
          },
          "loose": true,
          "includes": ["babel-plugin-transform-object-rest-spread"]
      }
  ], "stage-0"]
}`

**Comment by j-hannah** [comment]
I was having this issue and got it resolved by removing `babel-preset-stage-0` and adding latest `babel-preset-stage-1`.

I wasn't including 'stage-0' in the presets inside my webpack config, but it seemed to matter that it was present. Also, as @aarongodin mentioned, updating to latest babel may help. In my case, not the issue though.

**Comment by siddiq-rehman** [comment]
can some one please explain what is the preset. I couldnt find this in webpack configuration.. 
Thanks in advance

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
