### ISSUE TITLE
ERROR Module parse failed Unexpected token You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by glafrance** [babel/babel-loader#291]
Wow, I just hit the most insanely bizarre issue. 

I'm creating a React app that wraps around an ExtJS app. I put my components in a directory named "react_components", which is a sub-directory of the directory that contains index.js, webpack.config.js, and .babelrc.

When I renamed the "react_components" directory to "components", all is well. But when I then place that directory inside a directory named "react_app", I get the following error:

**ERROR in ./react_app_bullshit/components/header.js
Module parse failed: C:\MyBusinessDONOTDELETE\src\websites\extjs-react\workspace\xjsreact\react_app_bullshit\components\header.js Unexpected token (14
:6)
You may need an appropriate loader to handle this file type.**

If I rename directory "react_app" to "react_crap", no error.

If I rename directory to "react_ap", no error.

WTF?

**Comment by AlastairTaft** [comment]
I'm seeing a similar error message, all my builds are breaking now but I can't figure out why.

**Comment by shalinparmar** [comment]
Same here....is anyone looking into this?

**Comment by AlastairTaft** [comment]
I spent a few hours rolling back dependencies but couldn't narrow it down.

**Comment by abouthiroppy** [comment]
Could you show us your repository?

**Comment by AlastairTaft** [comment]
I should've read this issue a bit closer before I started checking dependencies.

I hit the error when I tried laying out my project in the structure described [here](https://github.com/boennemann/alle).

Basically it puts all your projects beneath a 'node_modules' folder so, in theory, developing peer dependent projects should be easier.

I guess this issue highlights that for some reason if the path contains an underscore the .babelrc file doesn't get picked up.

**Comment by guillaumewuip** [comment]
Having the same problem. Webpack builds everything fine when the path to the project contain no underscore but fail when there is one.

**Webpack config :**
```js
const webpackConfig = {
    entry:  ['babel-polyfill', './public/js/index.jsx'],
    module: {
        loaders: [{
            test:    /\.(js|jsx)$/,
            exclude: /node_modules/,
            loader:  'babel-loader',
            query:   {
                presets: ['es2015', 'react'],
            },
        }],
    },
    output: {
        path:     path.join(__dirname, 'public/build/js'),
        filename: 'bundle.js',
    },
    plugins: [new webpack.DefinePlugin({
        'process.config': {
            API_URL: process.env.API_URL,
        },
    })],
};
```

**Error :**
```
[18:56:20] Version: webpack 1.13.2
2016-09-30T20:57:03.830+02:00 Asset Size Chunks Chunk Names
2016-09-30T20:57:03.853+02:00bundle.js 1.24 MB 0 [emitted] main
2016-09-30T20:57:03.854+02:00ERROR in ./public/js/services/api.js
2016-09-30T20:57:03.875+02:00Module parse failed: /home/bas/app_7b98e727-33f3-47b4-850c-af04a72040da/node_modules/babel-loader/index.js?presets[]=react,presets[]=es2015!/home/bas/app_7b98e727-33f3-47b4-850c-af04a72040da/public/js/services/api.js Unexpected token (1:5)
2016-09-30T20:57:03.876+02:00You may need an appropriate loader to handle this file type.
2016-09-30T20:57:03.877+02:00SyntaxError: Unexpected token (1:5)
2016-09-30T20:57:03.878+02:00 at Parser.pp$4.raise (/home/bas/app_7b98e727-33f3-47b4-850c-af04a72040da/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
2016-09-30T20:57:03.879+02:00 at Parser.pp.unexpected (/home/bas/app_7b98e727-33f3-47b4-850c-af04a72040da/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
2016-09-30T20:57:03.880+02:00 at Parser.pp.expect (/home/bas/app_7b98e727-33f3-47b4-850c-af04a72040da/node_modules/webpack/node_modules/acorn/dist/acorn.js:597:28)
2016-09-30T20:57:03.881+02:00 at Parser.pp$3.parseParenAndDistinguishExpression (/home/bas/app_7b98e727-33f3-47b4-850c-af04a72040da/node_modules/webpack/node_modules/acorn/dist/acorn.js:1852:40)
2016-09-30T20:57:03.882+02:00 at Parser.pp$3.parseExprAtom (/home/bas/app_7b98e727-33f3-47b4-850c-af04a72040da/node_modules/webpack/node_modules/acorn/dist/acorn.js:1796:19)
2016-09-30T20:57:03.884+02:00 at Parser.pp$3.parseExprSubscripts (/home/bas/app_7b98e727-33f3-47b4-850c-af04a72040da/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
2016-09-30T20:57:04.017+02:00 at Parser.pp$3.parseMaybeUnary (/home/bas/app_7b98e727-33f3-47b4-850c-af04a72040da/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
2016-09-30T20:57:04.021+02:00 at Parser.pp$3.parseExprOps (/home/bas/app_7b98e727-33f3-47b4-850c-af04a72040da/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
2016-09-30T20:57:04.022+02:00 at Parser.pp$3.parseMaybeAssign (/home/bas/app_7b98e727-33f3-47b4-850c-af04a72040da/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
2016-09-30T20:57:04.022+02:00 at Parser.pp$3.parseMaybeConditional (/home/bas/app_7b98e727-33f3-47b4-850c-af04a72040da/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
```

**Beginning of `actions.js`**
```js
/* eslint no-alert:0 */

import * as api from './services/api';

export const INIT           = 'INIT';
...
```

**Comment by guillaumewuip** [comment]
Ok, just found the source of my error. It was not the underscore.
My webpack config inject the `API_URL` env var. The build crash when `API_URL="http://..."` instead of `API_URL="'http://...'"` (note the single quotes inside).
Actually, in './services/api.js', the two first lines are : 
```
import fetch from 'isomorphic-fetch';
const API_URL = process.config.API_URL;
```

**Comment by Jenner2017** [comment]
I have a similar problem but with angular, when trying to send data to a remote server sends me the following error: 
Failed to compile.

./src/app/service/news.service.ts
Module parse failed: Unexpected token (25:45)
You may need an appropriate loader to handle this file type.
|             .map(function (res) { return res; });
|     };
|     NewsService.prototype.addNew = function (, New) {
|         if ( === void 0) {  = new ; }
|         return this.http.post(this.domain, new )
 @ ./src/app/app.module.ts 12:21-54
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

can anybody help me

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
