### ISSUE TITLE
webpack outputs an error when parsing a file that has the word "Text" in the file name.

### ISSUE THREAD

**Issue by phandersson** [babel/babel-loader#385]
**I'm submitting a bug report**

**Webpack Version:**
1.14.0

**Babel Core Version**:
6.20.0

**Babel Loader Version**:
6.2.10

**Please tell us about your environment:**
Windows 10

**Current behavior:**
webpack outputs an error when trying to parse a JS file that has the word "Text" in the file name (in my case "TextField" or even "FieldText").
Saying i may need an appropriate loader to handle this file type:
```cmd
webpack: bundle is now INVALID.
webpack building...
webpack built d84e1e55d0badc5ca953 in 264ms

ERROR in ./core/components/fd/fields/FieldTextArea.js
Module parse failed: C:\Users\PA\Desktop\reactify\core\components\fd\fields\FieldTextArea.js Unexpected token (19:3)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (19:3)
    at Parser.pp$4.raise (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseParenAndDistinguishExpression (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:1861:32)
    at Parser.pp$3.parseExprAtom (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:1796:19)
    at Parser.pp$3.parseExprSubscripts (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExpression (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:1573:21)
    at Parser.pp$1.parseReturnStatement (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:839:33)
    at Parser.pp$1.parseStatement (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:699:34)
    at Parser.pp$1.parseBlock (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:2105:24)
    at Parser.pp$3.parseMethod (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:2075:10)
    at Parser.pp$1.parseClassMethod (C:\Users\PA\Desktop\reactify\node_modules\acorn\dist\acorn.js:1137:25)
 @ ./core/components/fd/Layout/Field.js 47:21-55
webpack: bundle is now VALID.
``` 

**Expected/desired behavior:**
to use the babel-loader as im doing with the rest of the files in the project.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
    * [webpack config and package.json](https://gist.github.com/phandersson/a458bdcca8a2503be474022aabc6b7f9)
    * create a file with the wording "Text" in the filename (in my case "TextField" or even "FieldText")
    * import the new file using the import statement into something like "Form.js" or any other file that is a part of the application
    * you should now get the error that webpack cant parse the file.

**Comment by danez** [comment]
In your webpack-config you have an exclude-filter /ext/, this matches `Text`

**Comment by phandersson** [comment]
Oh, that was one simple mistake. Thanks for noticing and i'm sorry for wasting your time @danez.
