### ISSUE TITLE
Cannot instantiate plugin babel-loader.

### ISSUE THREAD

**Issue by stevenvachon** [babel/babel-loader#387]
```shell
> webpack index.js index-browser.js -p --plugin=babel-loader
```
```
Cannot instantiate plugin babel-loader. (/project/node_modules/babel-loader/lib/index.js)
/project/node_modules/webpack/bin/convert-argv.js:261
				throw e;
				^

TypeError: Cannot read property 'slice' of undefined
    at Object.exports.getRemainingRequest (/project/node_modules/loader-utils/index.js:143:37)
    at new module.exports (/project/node_modules/babel-loader/lib/index.js:82:43)
    at loadPlugin (/project/node_modules/webpack/bin/convert-argv.js:258:12)
    at /project/node_modules/webpack/bin/convert-argv.js:471:25
    at ifArg (/project/node_modules/webpack/bin/convert-argv.js:193:5)
    at processOptions (/project/node_modules/webpack/bin/convert-argv.js:469:3)
    at processConfiguredOptions (/project/node_modules/webpack/bin/convert-argv.js:141:4)
    at module.exports (/project/node_modules/webpack/bin/convert-argv.js:115:10)
    at Object.<anonymous> (/project/node_modules/webpack/bin/webpack.js:153:40)
    at Module._compile (module.js:571:32)
```

Using latest versions of babel, babel-loader and webpack.

**Comment by stevenvachon** [comment]
The solution:
```shell
> webpack index.js index-browser.js -p --module-bind=babel-loader
```
