### ISSUE TITLE
Error on build when entry is typescript and only contents are import babel-polyfill

### ISSUE THREAD

**Issue by JayAndCatchFire** [babel/babel-loader#444]
I'm getting a strange error when my entry point is a typescript file and the only contents are `import 'babel-polyfill';`.  If I add any other code or comments to that file, it build just fine.  Also, if I change the file to a normal javascript file (.js) it builds fine.

Here's an example of the error:
```
ERROR in ./src/index.ts
Module build failed: TypeError: /home/REDACTED/code/babel-preset-env-error-example/src/index.ts: Cannot read property 'indexOf' of undefined
    at Object.relative (/home/REDACTED/code/babel-preset-env-error-example/node_modules/source-map/lib/util.js:206:15)
    at SourceMapConsumer_generatedPositionFor [as generatedPositionFor] (/home/REDACTED/code/babel-preset-env-error-example/node_modules/source-map/lib/source-map-consumer.j
s:731:21)
    at /home/REDACTED/code/babel-preset-env-error-example/node_modules/babel-core/lib/transformation/file/index.js:461:51
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/home/REDACTED/code/babel-preset-env-error-example/node_modules/source-map/lib/source-map-consumer.js:155:14)
    at File.mergeSourceMap (/home/REDACTED/code/babel-preset-env-error-example/node_modules/babel-core/lib/transformation/file/index.js:460:24)
    at File.generate (/home/REDACTED/code/babel-preset-env-error-example/node_modules/babel-core/lib/transformation/file/index.js:719:25)
    at File.transform (/home/REDACTED/code/babel-preset-env-error-example/node_modules/babel-core/lib/transformation/file/index.js:554:17)
    at /home/REDACTED/code/babel-preset-env-error-example/node_modules/babel-core/lib/transformation/pipeline.js:50:19
    at File.wrap (/home/REDACTED/code/babel-preset-env-error-example/node_modules/babel-core/lib/transformation/file/index.js:564:16)
    at Pipeline.transform (/home/REDACTED/code/babel-preset-env-error-example/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at transpile (/home/REDACTED/code/babel-preset-env-error-example/node_modules/babel-loader/lib/index.js:48:20)
    at /home/REDACTED/code/babel-preset-env-error-example/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/home/REDACTED/code/babel-preset-env-error-example/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)
```

And here's a link to a repository I created with just the minimal code to cause this: [JayAndCatchFire/babel-preset-env-error-example](https://github.com/JayAndCatchFire/babel-preset-env-error-example)

**Comment by loganfsmyth** [comment]
We have a new source map merging implementation that should avoid these issues. If this is still an issue on the most recent Babel version feel free to raise a new issue.
