### ISSUE TITLE
fileSystem.statSync is not a function

### ISSUE THREAD

**Issue by vshymanskyy** [babel/babel-loader#505]
Getting this error only on v7.1.2. When I downgrade to 7.1.1 - everything works.
```
Module build failed: TypeError: fileSystem.statSync is not a function
    at module.exports (.../node_modules/babel-loader/lib/utils/exists.js:7:25)
    at find (.../node_modules/babel-loader/lib/resolve-rc.js:13:9)
    at Object.module.exports (.../node_modules/babel-loader/lib/index.js:113:132)
```

**Comment by joboscribe** [comment]
Looks like in `lib/index.js`
```
var fileSystem = this.fs ? this.fs : fs;
```
`this.fs` exists but doesn't have the function `statSync`. When i changed it to 
```
var fileSystem = fs;
```
everything seemed to work. What's the goal in using `this.fs`? I didn't dig very far, does it allow for overriding it to something other than `fs`?

**Comment by danez** [comment]
@vshymanskyy @joboscribe can you post the output of the following commands:
```
npm ls webpack
npm ls enhanced-resolve
```

`this.fs` is the cached filesystem from webpack and it should support `statSync` since version 2.2.0 of webpack.

**Comment by joboscribe** [comment]
Sure:
```
$ npm ls webpack
/home/vagrant/src/project/site
└── webpack@3.5.5

$ npm ls enhanced-resolve
/home/vagrant/src/project/site
└─┬ webpack@3.5.5
  └── enhanced-resolve@3.4.1
```

But when i `$ npm ls --global` i get:
```
/usr/lib
├─┬ npm@2.15.11
  ...stuff...
└─┬ webpack@1.15.0
```
Because that's what i have specified. 

So, ultimately, the issue seems to be that i'm using a deprecated version of webpack because i'm lazy. Not sure if there's anything for you to fix at this point.

**Comment by danez** [comment]
if you use webpack 1.x please us babel-loader 6.x

**Comment by JackyTung** [comment]
@danez I also encounter same error msg, 
I write the comment under this issue [https://github.com/babel/babel-loader/issues/503#issuecomment-324251487](url)

my package version is 
```
babel-loader@7.1.2
webpack@2.7.0
```

so I don't why it still occur err

**Comment by JackyTung** [comment]
My temporarily solution is downgrade label-loader to 7.1.1

```
yarn add babel-loader@7.1.1 --dev
```

**Comment by CezaryDanielNowak** [comment]
I had this problem when updating babel-eslint and babel-loader from version 6 to 7. On 6.* It still works OK.

**Comment by paternalis** [comment]
I got this error with webpack@2.4.1, downgrading babel-loader from 7.1.2 to 7.1.1 did the trick. Kudos to @JackyTung

**Comment by monsterooo** [comment]
@danez solve my problems tks

**Comment by spearson23** [comment]
I had the same error with webpack@3.9.1.  Downgraded babel-loader and it worked.

**Comment by sangaline** [comment]
@spearson23, which version of `babel-loader` worked for you? I'm also using `webpack@3.9.1`, but I still get the error with all of the 6 and 7 `babel-loader` versions that I've tried.

**Comment by spearson23** [comment]
I downgraded to 7.1.1

**Comment by dudueasy** [comment]
Had the same error, thanks for posting, its really helpful!

**Comment by cmshiyas** [comment]
I encountered this error when i was using  "babel-loader": "^7.1.3", Change to babel-loader@6.2.5 worked!

**Comment by chosenvictim** [comment]
I am facing the same issue in babel loader 6.2.5.
`Module build failed: TypeError: fileSystem.statSync is not a function
    at module.exports (~/node_modules/babel-loader/lib/utils/exists.js:7:25)
    at find (~/node_modules/babel-loader/lib/resolve-rc.js:13:9)
    at Object.module.exports (~/node_modules/babel-loader/lib/index.js:113:132)
 @ ./index.js 11:11-30
webpack: Failed to compile.`

Node@8.9.2
webpack@1.15.0
webpack-dev-server@1.16.5
babel-core@6.14.0
babel-loader@6.2.5

I tried changing babel loader version to 7.1.1, but no luck.

**Comment by danez** [comment]
@chosenvictim If you get that error it clearly indicates you are using babel-loader >= 7.0.0 (and not 6.2.5) with webpack 1. Maybe you can check your node modules , package.json or lock file.

The line the error is thrown does not exist in babel-loader 6.x.

**Comment by dushi27** [comment]
Worked when I installed babel-loader 6.3. I'm using webpack 1.13.3

**Comment by chosenvictim** [comment]
@danez I am pretty sure that I am using babel-loader 6.2.5 and webpack 1.15.0
I checked with npm ls --depth=0

**Comment by farfromrefug** [comment]
I have the same issue with webpack 4.1.12 and babel-loader 7.1.4. The only solution for is to modify the code not to use the cache version. Would be better to have a fix.
Thanks

**Comment by noonii** [comment]
babel-loader 8.0.4
webpack 4.19.0

Facing same issue. I thought 4.x was compatible with 8.x ? I can't downgrade major versioning as it will break multiple projects, so is there a specific version between 8 and 4 that works?
