### ISSUE TITLE
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions.

### ISSUE THREAD

**Issue by gabrielcarneiro97** [babel/babel-loader#575]
I'm trying to use babel-loader to pack some imported functions to export it to firebase, but the same error is happening every time.

 `Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions.`

I just don't know what to try anymore.

**webpack.config.js**
```
module.exports = {
  entry: './src/index.js',
  output: { path: __dirname, filename: 'index.js' },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader'
        }
      }
    ]
  }
}
```

**Full error**
```
ERROR in ../src/components/services/index.js
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions.
    at createDescriptor (C:\Users\Gabriel\Projetos\danfy\functions\node_modules\@babel\core\lib\config\config-descriptor
s.js:158:11)
    at C:\Users\Gabriel\Projetos\danfy\functions\node_modules\@babel\core\lib\config\config-descriptors.js:101:12
    at Array.map (<anonymous>)
    at createDescriptors (C:\Users\Gabriel\Projetos\danfy\functions\node_modules\@babel\core\lib\config\config-descripto
rs.js:100:27)
    at createPresetDescriptors (C:\Users\Gabriel\Projetos\danfy\functions\node_modules\@babel\core\lib\config\config-des
criptors.js:92:10)
    at C:\Users\Gabriel\Projetos\danfy\functions\node_modules\@babel\core\lib\config\config-descriptors.js:64:19
    at presets (C:\Users\Gabriel\Projetos\danfy\functions\node_modules\@babel\core\lib\config\config-descriptors.js:54:2
5)
    at mergeChainOpts (C:\Users\Gabriel\Projetos\danfy\functions\node_modules\@babel\core\lib\config\config-chain.js:293
:68)
    at C:\Users\Gabriel\Projetos\danfy\functions\node_modules\@babel\core\lib\config\config-chain.js:246:7
    at buildRootChain (C:\Users\Gabriel\Projetos\danfy\functions\node_modules\@babel\core\lib\config\config-chain.js:82:
20)
    at loadConfig (C:\Users\Gabriel\Projetos\danfy\functions\node_modules\@babel\core\lib\config\index.js:50:53)
    at transformSync (C:\Users\Gabriel\Projetos\danfy\functions\node_modules\@babel\core\lib\transform-sync.js:13:36)
    at Object.transform (C:\Users\Gabriel\Projetos\danfy\functions\node_modules\@babel\core\lib\transform.js:20:65)
    at transpile (C:\Users\Gabriel\Projetos\danfy\functions\node_modules\babel-loader\lib\index.js:55:20)
    at Object.module.exports (C:\Users\Gabriel\Projetos\danfy\functions\node_modules\babel-loader\lib\index.js:179:20)
 @ ./src/index.js 9:16-56
```
**../src/components/services/index.js**
```
export * from './xml.service'
export * from './firebase.service'
export * from './validador.service'
export * from './calculador.service'
export * from './store.service'
export * from './assets.service'
export * from './globals'
```

**Comment by vitolipari** [comment]
Do you find a fix?

**Comment by dannyk08ib** [comment]
same problem here too 

```js
// webpack.config.js
      {
        test: /\.(js|jsx)$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              '@babel/env',
              '@babel/stage-0',
              '@babel/react',
              '@babel/es2015',
            ],
            plugins: [
              require('@babel/plugin-proposal-object-rest-spread'),
              require('@babel/plugin-proposal-class-properties')
            ]
          }
        }
      },

```


```json
// package.json
    "@babel/cli": "^7.0.0-beta.44",
    "@babel/core": "^7.0.0-beta.44",
    "@babel/plugin-proposal-class-properties": "^7.0.0-beta.44",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0-beta.44",
    "@babel/preset-env": "^7.0.0-beta.44",
    "@babel/preset-es2015": "^7.0.0-beta.44",
    "@babel/preset-react": "^7.0.0-beta.44",
    "@babel/preset-stage-0": "^7.0.0-beta.44",
    "@types/react": "^16.3.9",
    "@types/react-dom": "^16.0.5",
    "babel-loader": "^8.0.0-beta.2"

```

**Comment by Tsury** [comment]
1+

**Comment by TSMMark** [comment]
@dannyk08ib I'm not sure of the rest of your setup, but since to me your webpack.config.js looks fine, is there a chance you have a `.babelrc` file that is erroneous?

If that's the case, you could try the `babelrc: false` babel-loader query option. If my understanding is correct, it ensures that even if you have a `.babelrc` file it will be ignored by webpack.

```
    loader: 'babel-loader',
      query: {
        babelrc: false,
```

**Comment by dannyk08ib** [comment]
I decided not to upgrade until things are resolved, the build would not compile with everything I tried: changing versions, changing the settings in the config && rc file, etc

will try again soon, and will post here in case someone has an issue waiting to be resolved

**Comment by edwardchase** [comment]
@d3alek  should i install that globally?

**Comment by d3alek** [comment]
No, global install is not needed. Just to clarify - the solution for me was to replace `babel-preset-react` in `package.json` with `@babel/preset-react`. The `npm install` command above simply put the correct (latest) version of `@babel/preset-react` in my `devDependencies`, and I manually removed `babel-preset-react`.

**Comment by arthurpf** [comment]
I found a solution using `babelrc: false` under options. Using under query gaves and error.
`{
				// JS Rules
				test: /\.js$/,
				exclude: /(node_modules|bower_components)/,
				use: {
					loader: 'babel-loader',
					options: {
						babelrc: false,
						presets: ['@babel/preset-env']
					}
				}
			}`
