### ISSUE TITLE
dep.getResourceIdentifier is not a function

### ISSUE THREAD

**Issue by arahansen** [babel/babel-loader#595]
**I'm submitting a bug report**

**Webpack Version:**
4.1.1

**Babel Core Version**:
7.0.0-beta.40

**Babel Loader Version**:
7.1.4

**Please tell us about your environment:**
OSX 10.12.6

**Current behavior:**
I'm getting a deprecation error when trying to build my babel project. Stack trace:
```
(node:69271) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
TypeError: dep.getResourceIdentifier is not a function
    at addDependency (/Users/ahansen/webdev/iris/node_modules/webpack/lib/Compilation.js:387:30)
    at iterationOfArrayCallback (/Users/ahansen/webdev/iris/node_modules/webpack/lib/Compilation.js:78:3)
    at addDependenciesBlock (/Users/ahansen/webdev/iris/node_modules/webpack/lib/Compilation.js:407:5)
    at Compilation.processModuleDependencies (/Users/ahansen/webdev/iris/node_modules/webpack/lib/Compilation.js:418:4)
    at afterBuild (/Users/ahansen/webdev/iris/node_modules/webpack/lib/Compilation.js:686:13)
    at buildModule.err (/Users/ahansen/webdev/iris/node_modules/webpack/lib/Compilation.js:714:8)
    at callback (/Users/ahansen/webdev/iris/node_modules/webpack/lib/Compilation.js:342:35)
    at module.build.error (/Users/ahansen/webdev/iris/node_modules/webpack/lib/Compilation.js:378:12)
    at handleParseResult (/Users/ahansen/webdev/iris/node_modules/webpack/lib/NormalModule.js:363:12)
    at doBuild.err (/Users/ahansen/webdev/iris/node_modules/webpack/lib/NormalModule.js:385:6)
    at runLoaders (/Users/ahansen/webdev/iris/node_modules/webpack/lib/NormalModule.js:264:12)
    at /Users/ahansen/webdev/iris/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Users/ahansen/webdev/iris/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at iterateNormalLoaders (/Users/ahansen/webdev/iris/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/ahansen/webdev/iris/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at Object.context.callback (/Users/ahansen/webdev/iris/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.module.exports (/Users/ahansen/webdev/iris/node_modules/babel-loader/lib/index.js:182:8)
    at LOADER_EXECUTION (/Users/ahansen/webdev/iris/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/ahansen/webdev/iris/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/ahansen/webdev/iris/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/ahansen/webdev/iris/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/ahansen/webdev/iris/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/ahansen/webdev/iris/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /Users/ahansen/webdev/iris/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:505:3)
```

**Expected/desired behavior:**
babel-loader should work with webpack@4.x while using babel@6.x

I'm not sure if this is an issue that's been seen before, but I'm not seeing it when upgrading to babel-loader@8.x. However, v8 seems to require upgrading to babel 7 which isn't an option for my project at this point.

**Comment by loganfsmyth** [comment]
I don't think this error is related to `babel-loader`, as far as I can tell. `babel-loader` is mentioned because you have it enabled, but the error seems to happen well after `babel-loader` is done doing its thing.

Also the deprecation warning is likely unrelated to the exception, and just happens to be printed before it.

I'd recommend talking to Webpack folks.

**Comment by xtuc** [comment]
I found a similar issue on the Webpack issue tracker https://github.com/webpack/webpack/issues/6675#issuecomment-371639631
