### ISSUE TITLE
Cannot find module 'debug' on running webpack

### ISSUE THREAD

**Issue by Moghul** [babel/babel-loader#604]
## **BEFORE YOU SUBMIT** please read the following:

*Delete what isn't applicable below*
**I'm submitting a bug report**

**Webpack Version:**
4.1.0
**Babel Core Version**:
6.0.0
**Babel Loader Version**:
7.1.4

**Please tell us about your environment:**
Ubuntu 16.04
**Current behavior:**
When running the webpack command, it throws an exception for every file it's meant to handle regardless of what it looks like. Without the babel-loader, webpack builds fine.

Unfortunately, it seems to be complaining about some missing module called 'debug' (?) which I don't reference or use anywhere.

**Expected/desired behavior:**
Hoping babel-loader will fix my issue with webpack bundles not working in IE10. I use 'const' and IE 10 and lower is a peach.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

My config file:

```
module.exports = {
    entry: {
        wideLayout: [
            vendor + 'jquery/dist/jquery.min.js',
            vendor + 'jquery-ui-dist/jquery-ui.min.js',
            vendor + 'bootstrap/dist/js/bootstrap.min.js',
            vendor + 'blueimp-file-upload/js/jquery.iframe-transport.js',
            vendor + 'loggly-jslogger/dist/loggly.tracker-2.2.2.min.js',
            sharedScripts + 'utils/common-utils.js',
            sharedScripts + 'utils/common-popup-utils.js',
            sharedScripts + 'utils/dialog.js',
            modules + 'layout.js'
        ]
    },
    output: {
        path: destinationDirectory,
        filename: '[name].bundle.[chunkhash].js',
        libraryTarget: 'var',
        library: 'Layout'
    },
    module: {
        rules: ([
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: vendor + "babel-loader",
                    options: {
                        presets: ['@babel/presets-env'],
                        plugins: ['@babel/plugin-transform-runtime'],
                        babelrc: false
                    }
                }
            },
            {
                test: /\.scss$/,
                use: ExtractTextPlugin.extract({
                    use: [{
                        loader: vendor + "css-loader",
                        options: {
                            alias: {
                                "../fonts/bootstrap": vendor + "/bootstrap-sass/assets/fonts/bootstrap",
                                "../images/": vendor + "bootstrap-sass/assets/images/"
                            }
                        }
                    }, {
                        loader: vendor + "sass-loader",
                        options: {
                            includePaths: [
                                path.resolve(vendor)
                            ]
                        }
                    }]
                })
            }
        ]).concat(defaultRulesConfig)
    },
    resolve: {
        alias: {
            $: path.resolve(__dirname, vendor + 'jquery/dist/jquery.min.js'),
            _LTracker: path.resolve(__dirname, vendor + 'loggly-jslogger/dist/loggly.tracker-2.2.2.min.js')
        },
        modules: [sourceDirectory, vendor, sharedScripts, sharedAssets]
    },
    plugins: defaultPluginConfig.concat([
        new FileChangerPlugin({
            change: [
                createReplacementConfig(layoutsDirectory + '/Default.html', ['defaultLayout'])
            ]
        })
    ])
};
```

The resulting trace looks like this, and is the same for every non-vendor file in that entry:

```
ERROR in ../shared-scripts/utils/dialog.js
Module build failed: Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (/usr/local/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/path/to/node_modules/babel-traverse/lib/path/index.js:17:15)
    at Module._compile (/usr/local/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (/usr/local/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/path/to/node_modules/babel-traverse/lib/index.js:10:13)
    at Module._compile (/usr/local/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (/usr/local/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/path/to/node_modules/babel-template/lib/index.js:69:22)
    at Module._compile (/usr/local/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (/usr/local/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/path/to/node_modules/babel-helpers/lib/helpers.js:5:22)
    at Module._compile (/usr/local/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (/usr/local/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
 @ multi ./../node_modules/jquery/dist/jquery.min.js ./../node_modules/jquery-ui-dist/jquery-ui.min.js ./../node_modules/bootstrap/dist/js/bootstrap.min.js ./../node_modules/blueimp-file-upload/js/jquery.iframe-transport.js ./../node_modules/loggly-jslogger/dist/loggly.tracker-2.2.2.min.js ./../shared-scripts/utils/common-utils.js ./../shared-scripts/utils/common-popup-utils.js ./../shared-scripts/utils/dialog.js ./modules/layout.js
```

I haven't been able to locate an issue like this through google, so here I am.

EDIT: OOOk.... so... `npm i -g debug` has changed my build error to

```
ERROR in ./path/to/shared-scripts/utils/dialog.js
    Module build failed: Error: Cannot find module './src/node'
```
That's... something.

**Comment by loganfsmyth** [comment]
I would recommend deleting and re-installing `node_modules`. It sounds like your local dependencies have become corrupted somehow.

**Comment by Moghul** [comment]
You were right. My .yarnclean file was deleting a /src/ directory.

**Comment by 1eandro** [comment]
I was getting the same error and it was also solved by just deleting the node_modules folder and then installing all the local dependencies again
