### ISSUE TITLE
Setting options

### ISSUE THREAD

**Issue by eranimo** [babel/babel-loader#61]
I get this error whenever I run webpack:
```
ERROR in ./src/client/app.jsx
Module build failed: ReferenceError: Unknown option: stage
    at File.normalizeOptions (/Users/kaelan/work/apps/hn-blog-new/node_modules/babel-core/lib/babel/transformation/file.js:91:15)
    at new File (/Users/kaelan/work/apps/hn-blog-new/node_modules/babel-core/lib/babel/transformation/file.js:70:22)
    at Object.transform (/Users/kaelan/work/apps/hn-blog-new/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at transpile (/Users/kaelan/work/apps/hn-blog-new/node_modules/babel-loader/index.js:54:24)
    at Object.module.exports (/Users/kaelan/work/apps/hn-blog-new/node_modules/babel-loader/index.js:43:24)
 @ multi app
```

I'm usign babel-loader like this:
```js
{
    test: /\.jsx?$/,
    loaders: ['react-hot', 'babel-loader?stage=0'],
    exclude: /node_modules/
},
```

It looks like I'm passing the stage option correctly, removing it solves the error but now generators don't work. Any ideas?

**Comment by sebmck** [comment]
Upgrade to the latest Babel version. You're on 4.x instead of 5.x.

**Comment by eranimo** [comment]
Thanks!

**Comment by isaacanet** [comment]
199999999999999999990165105610
