### ISSUE TITLE
./utils/exists ERROR with Webpack4

### ISSUE THREAD

**Issue by Adherentman** [babel/babel-loader#610]
## **BEFORE YOU SUBMIT** please read the following:

*Delete what isn't applicable below*
**I'm submitting a bug report**

**Webpack Version:**
4.6.0

**Babel Core Version**:
6.26.0

**Babel Loader Version**:
7.1.4

**Please tell us about your environment:**
OSX 10.13.4

**Current behavior:**
```shell
ERROR in ../src/index.js
Module build failed: Error: Cannot find module './utils/exists'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xuzihao/simple-forum/server/node_modules/babel-loader/lib/config.js:3:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xuzihao/simple-forum/server/node_modules/babel-loader/lib/index.js:5:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
 @ multi react-hot-loader/patch webpack-hot-middleware/client ../src/index.js
```

**index.js**
```js
import React from 'react';
import ReactDOM from 'react-dom';
//import { Provider } from 'react-redux';
import { ApolloClient, gql, HttpLink, InMemoryCache, ApolloLink } from 'apollo-boost';
import ApolloProvider from 'react-apollo';

import { client } from './env';
import App from './components/App';


// client.query({query: gql`{books{title}}`}).then(console.log);

ReactDOM.render(
    <ApolloProvider client={client}>
      <App />
    </ApolloProvider>,
  document.getElementById('root')
);
```

**webpack**
```js
module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env']
          }
        }
      },
```

**I don't know where I used./utils/exists, but it looks like Babel.**

**Comment by danez** [comment]
I think you are mixing versions up here. Looking at the stacktrace the version of babel-loader you are using is definitely not 7.1.4 but rather one of the 8.0.0 betas. version 8.0 of babel-loader requires babel v7.

**Comment by Adherentman** [comment]
@danez 
This is my current configuration
```javascript
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",

{
        test: /(\.jsx|\.js)$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: {
          presets: ['env', 'react'],
        },
      },
```
And then work
