### ISSUE TITLE
Error When leveraging Cache

### ISSUE THREAD

**Issue by iammerrick** [babel/babel-loader#72]
When I set the cache directory I get the following stack trace:

```
Module build failed: Error: Final loader didn't return a Buffer or String
    at DependenciesBlock.onModuleBuild (/Users/Merrick/Developer/Domo/DomoWeb/DomoWeb/mobile-web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:299:42)
    at nextLoader (/Users/Merrick/Developer/Domo/DomoWeb/DomoWeb/mobile-web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/Merrick/Developer/Domo/DomoWeb/DomoWeb/mobile-web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/Merrick/Developer/Domo/DomoWeb/DomoWeb/mobile-web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /Users/Merrick/Developer/Domo/DomoWeb/DomoWeb/mobile-web/node_modules/babel-loader/index.js:58:7
    at /Users/Merrick/Developer/Domo/DomoWeb/DomoWeb/mobile-web/node_modules/babel-loader/lib/fs-cache.js:135:24
    at /Users/Merrick/Developer/Domo/DomoWeb/DomoWeb/mobile-web/node_modules/babel-loader/lib/fs-cache.js:40:14
    at Gunzip.onEnd (zlib.js:227:5)
    at Gunzip.emit (events.js:129:20)
    at _stream_readable.js:908:16
```

Any ideas? It works without cache just fine. :-)

**Comment by Couto** [comment]
Which version are you using? The current version should be 5.1.3

**Comment by iammerrick** [comment]
@Couto Woah 5.1.0 -> 5.1.3 Fixed it! Thank you!

**Comment by Couto** [comment]
:+1:
