### ISSUE TITLE
babel-loader breaks with babel monorepo v7.2.0

### ISSUE THREAD

**Issue by Fandekasp** [babel/babel-loader#740]
**I'm submitting a bug report**

**Webpack Version:**
4.26.1

**Babel Core Version**:
7.2.0

**Babel Loader Version**:
8.0.4

**Please tell us about your environment:**
Linux

**Current behavior:**
<details><summary>error traceback on build</summary>

```js
ERROR in ./src/lib/error.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: path.isClassPrivateMethod is not a function
    at verifyUsedFeatures (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/helper-create-class-features-plugin/lib/features.js:46:12)
    at PluginPass.Class (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/helper-create-class-features-plugin/lib/index.js:69:42)
    at newFn (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitQueue (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:124:21)
    at TraversalContext.visitMultiple (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/index.js:94:17)
    at traverse (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/index.js:76:12)
    at transformFile (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/core/lib/transformation/index.js:88:29)
    at runSync (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/core/lib/transformation/index.js:45:3)
    at runAsync (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at process.nextTick (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/core/lib/transform.js:34:34)
    at process._tickCallback (internal/process/next_tick.js:61:11)
 @ ./src/lib/api.js 1:0-30 15:17-24 26:22-29
 @ ./src/sagas/subscription.js
 @ ./src/sagas/index.js
 @ ./src/configureStore.js
 @ ./src/app.js
 @ multi ./src/app.js

ERROR in ./src/components/Root.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: path.isClassPrivateMethod is not a function
    at verifyUsedFeatures (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/helper-create-class-features-plugin/lib/features.js:46:12)
    at PluginPass.Class (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/helper-create-class-features-plugin/lib/index.js:69:42)
    at newFn (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/home/dori/Projects/work/company/project/subproject/node_modules/@babel/traverse/lib/path/context.js:95:18)
 @ ./src/app.js 3:0-37 10:36-40
 @ multi ./src/app.js
```
</details>

**Expected/desired behavior:**
build works as expected (like Webpack 4.26.1 + Babel 7.1.5 + Babel loader 8.0.4)

* **What is the motivation / use case for changing the behavior?**
Upgrading Babel monorepo to v7.2.0
https://babeljs.io/blog/2018/12/03/7.2.0

**Comment by xmsz** [comment]
Same Problem when I update the Babel

**Comment by smonn** [comment]
I ran into this issue too after upgrading to Babel 7.2.0. One workaround is to delete the `node_modules` directory and the `package-lock.json` or `yarn.lock` file. Doing that solved the issue for me. See this issue for details: https://github.com/babel/babel/issues/9120

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/9121, it will be released soon.

**Comment by Fandekasp** [comment]
@nicolo-ribaudo was gonna say it's not related, but you're also the one who commented in https://github.com/babel/babel/issues/9120 haha.
Thanks!

**Comment by Fandekasp** [comment]
since rewriting the yarn.lock also fixes the issue, I'm closing it :+1:

**Comment by nicolo-ribaudo** [comment]
That PR fixes the `path.isClassPrivateMethod is not a function` error, so it is correct :stuck_out_tongue:
