### ISSUE TITLE
Function names off by 1 in error stack trace

### ISSUE THREAD

**Issue by marvinhagemeister** [babel/babel-loader#786]
## **BEFORE YOU SUBMIT** please read the following:

**I'm submitting a bug report**

**Webpack Version:**
4.30.0

**Babel Core Version**:
7.4.3

**Babel Loader Version**:
8.0.5

**Please tell us about your environment:**
Linux

**Current behavior:**

Currently the function names are off by 1 starting from the second entry in a stack trace. The second function call should be named `bar` and the third `bob`. Although the names are wrong, both the column and line number remain correct.

```txt
Error:
    at foo (/home/marvinh/dev/test/webpack-sourcemap/dist/webpack:/src/foo.js:2:15)
    at foo (/home/marvinh/dev/test/webpack-sourcemap/dist/webpack:/src/foo.js:6:3)
    at bar (/home/marvinh/dev/test/webpack-sourcemap/dist/webpack:/src/foo.js:10:3)
    ...more
```

**Expected/desired behavior:**

```txt
Error:
    at foo (/home/marvinh/dev/test/webpack-sourcemap/dist/webpack:/src/foo.js:2:15)
    at bar (/home/marvinh/dev/test/webpack-sourcemap/dist/webpack:/src/foo.js:6:3)
    at bob (/home/marvinh/dev/test/webpack-sourcemap/dist/webpack:/src/foo.js:10:3)
    ...more
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

Repo where the issue can be reproduced https://github.com/marvinhagemeister/babel-loader-bug:

1. `git clone https://github.com/marvinhagemeister/babel-loader-bug`
2. `cd babel-loader-bug`
3. `yarn install`
4. `yarn test`

Compare this to the expected result with `yarn test-expected`. I tried reproducing it with the babel cli alone, but I can't reproduce it there.

* **What is the expected behavior?**

Stack trace should be correct.

* **What is the motivation / use case for changing the behavior?**

Wrong stack traces are confusing :)

**Comment by marvinhagemeister** [comment]
Nevermind, after poking around some more I'm actually able to reproduce it in the cli. Moving the issue there.
