### ISSUE TITLE
Failed to compile after upgrade from 8.0.6 to 8.1.0

### ISSUE THREAD

**Issue by ynwd** [babel/babel-loader#835]
Failed to compile after upgrade from 8.0.6 to 8.1.0
Webpack version: **4.42.0**

```
ERROR in ./src/components/App.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: /Users/user/Documents/sample/src/components/App.tsx: Unknown helper createSuper
    at loadHelper (/Users/user/Documents/sample/node_modules/@babel/helpers/lib/index.js:225:27)
    at Object.ensure (/Users/user/Documents/sample/node_modules/@babel/helpers/lib/index.js:270:3)
    at File.addHelper (/Users/user/Documents/sample/node_modules/@babel/core/lib/transformation/file/file.js:203:15)
    at pushInheritsToBody (/Users/user/Documents/sample/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:471:384)
    at pushConstructorToBody (/Users/user/Documents/sample/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:461:5)
    at pushConstructor (/Users/user/Documents/sample/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:449:5)
    at pushBody (/Users/user/Documents/sample/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:187:11)
    at buildBody (/Users/user/Documents/sample/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:133:5)
    at classTransformer (/Users/user/Documents/sample/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:537:5)
    at transformClass (/Users/user/Documents/sample/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:573:10)
 @ ./src/components/index.tsx 7:0-24 8:41-44
 @ multi ./src/components/index.tsx webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000&reload=true
```

**Comment by adascal** [comment]
Possibly related: https://github.com/facebook/create-react-app/issues/8680

**Comment by existentialism** [comment]
@adascal seems like a different error?

**Comment by adascal** [comment]
Error is different, but problem appeared exactly after `babel` release :)

**Comment by existentialism** [comment]
@adascal gotcha, yeah, not 100% sure, but they seem unrelated. I already posted in the CRA thread about that issue.

**Comment by existentialism** [comment]
@ynwd https://github.com/babel/babel/pull/11298

**Comment by existentialism** [comment]
The fix for this was released in https://github.com/babel/babel/releases/tag/v7.9.2!
