### ISSUE TITLE
Multiple configs with babel-loader and api.caller() in Babel config cause occasional error

### ISSUE THREAD

**Issue by MrSlide** [babel/babel-loader#838]
**I'm submitting a bug report**

**Webpack Version:**
4.42.0

**Babel Core Version**:
7.9.0

**Babel Loader Version**:
8.1.0

**Please tell us about your environment:**
OSX 10.15.3

**Current behavior:**

When exporting an array of configurations in the `webpack.config.js` file and using `babel-loader` with a `babel.config.js` file that exports a function and uses the `api.caller()` call to dynamically set configuration options, the build will only complete successfully occasionally in what appears to be a race condition.

```
/project/node_modules/webpack/lib/buildChunkGraph.js:363
					for (const refModule of blockInfo.modules) {
					                                  ^

TypeError: Cannot read property 'modules' of undefined
    at visitModules (/project/node_modules/webpack/lib/buildChunkGraph.js:363:40)
    at buildChunkGraph (/project/node_modules/webpack/lib/buildChunkGraph.js:702:2)
    at Compilation.seal (/project/node_modules/webpack/lib/Compilation.js:1315:3)
    at /project/node_modules/webpack/lib/Compiler.js:675:18
    at /project/node_modules/webpack/lib/Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/project/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/project/node_modules/webpack/lib/Compilation.js:1253:28)
    at /project/node_modules/webpack/lib/Compiler.js:672:17
    at eval (eval at create (/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /project/node_modules/webpack/lib/Compilation.js:1185:12
    at /project/node_modules/webpack/lib/Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
```

https://gist.github.com/MrSlide/82394072ebbe6aedfed46bbde54e7e0a

* **What is the expected behavior?**

The build will complete successfully for the multiple configurations provided to Webpack consistently.

* **What is the motivation / use case for changing the behavior?**

In my build I am creating different bundles for browsers that have different levels of JavaScript support to be able to provide smaller and more performant code to modern browsers while still supporting legacy browsers.

**Comment by nicolo-ribaudo** [comment]
That error is a webpack bug: https://github.com/webpack/webpack/issues/7520, https://github.com/webpack/webpack/issues/7525.

In webpack 5 they are explicitly checking if `blockInfo` (renamed to `blockModules`) is `undefined` before using it:
https://github.com/webpack/webpack/blob/ac022f3ff2509f480be6f43fb1d656e5dcbd0b06/lib/buildChunkGraph.js#L403
