### ISSUE TITLE
Error - Property name expected type of string but got null 

### ISSUE THREAD

**Issue by tenjojeremy** [babel/babel-loader#840]
Getting `Property name expected type of string but got null` error

![err](https://user-images.githubusercontent.com/25231946/77552596-1da33980-6e8a-11ea-9608-a172193dbec7.jpg)

`babel.config.js`
```js
module.exports = {
  presets: [
    [
      require('@babel/preset-env'),
      {
        targets: 'defaults, not ie <= 11, not edge > 0, not IE_Mob 11',
        modules: false
      }
    ],
    require('@babel/preset-react')
  ],
  plugins: [
    require('react-hot-loader/babel'),
    require('@babel/plugin-transform-regenerator'),
    require('@babel/plugin-syntax-dynamic-import'),
    require('@babel/plugin-syntax-throw-expressions'),
    require('@babel/plugin-transform-runtime'),
    require('babel-plugin-styled-components')
  ],
  env: {
    production: {
      plugins: [require('babel-plugin-transform-react-remove-prop-types')]
    }
  }
}
```

`package.json`

```json
  "dependencies": {
    "@babel/core": "^7.9.0",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-syntax-throw-expressions": "^7.8.3",
    "@babel/plugin-transform-regenerator": "^7.8.7",
    "@babel/plugin-transform-runtime": "^7.9.0",
    "@babel/preset-env": "^7.9.0",
    "@babel/preset-react": "^7.9.4",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^25.1.0",
    "babel-loader": "^8.1.0",
    "babel-plugin-styled-components": "^1.10.7",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "react-hot-loader": "^4.12.20"
  }

```

**Comment by nicolo-ribaudo** [comment]
What is the full stack trace of the error=

**Comment by tenjojeremy** [comment]
> What is the full stack trace of the error?

Hello @nicolo-ribaudo 

![full](https://user-images.githubusercontent.com/25231946/77595642-1d2d9180-6ed0-11ea-9ace-25ddcc6984e3.jpg)

```
Failed to compile.

./src/data/tv/tvFavorites.state.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: C:\Dev\Personal_Projects\sites\tv-guide\src\data\tv\tvFavorites.state.js: Property name expected type of string but got null
    at validate (C:\Dev\Personal_Projects\sites\tv-guide\node_modules\@babel\types\lib\definitions\utils.js:160:13)
    at Object.validate (C:\Dev\Personal_Projects\sites\tv-guide\node_modules\@babel\types\lib\definitions\utils.js:229:7)
    at validateField (C:\Dev\Personal_Projects\sites\tv-guide\node_modules\@babel\types\lib\validators\validate.js:24:9)
    at validate (C:\Dev\Personal_Projects\sites\tv-guide\node_modules\@babel\types\lib\validators\validate.js:17:3)
    at builder (C:\Dev\Personal_Projects\sites\tv-guide\node_modules\@babel\types\lib\builders\builder.js:38:27)
    at Object.Identifier (C:\Dev\Personal_Projects\sites\tv-guide\node_modules\@babel\types\lib\builders\generated\index.js:337:31)
    at C:\Dev\Personal_Projects\sites\tv-guide\node_modules\regenerator-transform\lib\hoist.js:32:29
    at Array.forEach (<anonymous>)
    at varDeclToExpr (C:\Dev\Personal_Projects\sites\tv-guide\node_modules\regenerator-transform\lib\hoist.js:29:23)
    at exit (C:\Dev\Personal_Projects\sites\tv-guide\node_modules\regenerator-transform\lib\hoist.js:51:20)
    at NodePath._call (C:\Dev\Personal_Projects\sites\tv-guide\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (C:\Dev\Personal_Projects\sites\tv-guide\node_modules\@babel\traverse\lib\path\context.js:42:17)
    at NodePath.visit (C:\Dev\Personal_Projects\sites\tv-guide\node_modules\@babel\traverse\lib\path\context.js:99:8)
    at TraversalContext.visitQueue (C:\Dev\Personal_Projects\sites\tv-guide\node_modules\@babel\traverse\lib\context.js:112:16)
    at TraversalContext.visitMultiple (C:\Dev\Personal_Projects\sites\tv-guide\node_modules\@babel\traverse\lib\context.js:79:17)
    at TraversalContext.visit (C:\Dev\Personal_Projects\sites\tv-guide\node_modules\@babel\traverse\lib\context.js:138:19)
```

**Comment by lihao-id** [comment]
I have the same error

**Comment by JLHwung** [comment]
Closing this as it is an upstream issue: https://github.com/facebook/regenerator/pull/390

The error is thrown because `transform-regenerator` is enabled but `transform-destructuring` is not enabled. i.e.

```js
const hello = async () => {
  const he = { ll: '2' }
  const { ll } = he
}
```

Regenerator does not recognize `{ ll }` in the `const { ll } = he`.

However, if your targets have already natively supported destrucutring `const { ll } = he`, then they would also support generator so you don't need `transform-regenerator` at all. In this case please use `@babel/plugin-transform-async-to-generator`.
