### ISSUE TITLE
Module build failed (from ./node_modules/babel-loader/lib/index.js)  while compiling JS via Jenkins

### ISSUE THREAD

**Issue by sridharpanneer** [babel/babel-loader#855]
**I'm submitting a bug report**

Im getting below error while compiling my script in Staging instance using Jenkins. It works good in my development sandbox instance
Platform : Salesforce commerce cloud

[1m[31mERROR in ./cartridges/app_storefront_base/cartridge/client/default/js/thirdParty/bootstrap.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
/var/lib/jenkins/workspace/stageguel/Dependencies/branches/node_modules/schema-utils/dist/util/hints.js:16
  const currentSchema = { ...schema
                          ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/lib/jenkins/workspace/stageguel/Dependencies/branches/node_modules/schema-utils/dist/ValidationError.js:11:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
 @ ./cartridges/app_guel_core/cartridge/client/default/js/main.js 45:0-36[39m[22m
	
**Package.json** file in staging
```
   "@babel/core": "^7.0.0-beta.51",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0-beta.51",
    "@babel/preset-env": "^7.0.0-beta.51",
    "@tridnguyen/config": "^2.3.1",
    "babel-loader": "^8.0.0-beta.3",
```
Note: this is same configuration in my local dev sandbox instance. i dont get any error while compiling JS

**Comment by JLHwung** [comment]
The error is thrown from node.js because `schema-utils` requires `node >= 8.9.0`. Please upgrade the node version on Jenkins.
