### ISSUE TITLE
Error encountered - consumer.computeColumnSpans is not a function - in merge-map.js line 146

### ISSUE THREAD

**Issue by mistergibson** [babel/babel-loader#870]
**I'm submitting a bug report**

**Webpack Version:**
4.42.1

**Babel Core Version**:
7.11.2

**Babel Loader Version**:
8.1.0

**Please tell us about your environment:**
Linux

**Current behavior:**
The following error is given when attempting to compile a large javascript file (9.2MB long and CANNOT be broken up) in electron-builder, which relies upon babel to process and load the source code. NOTE: "consumer.computeColumnSpans" is not even in the source code of gxg.js -- not even there.

ERROR in ./resources/gxg.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    TypeError: /home/mistergibson/Documents/Development/gxg-studio/resources/gxg.js: consumer.computeColumnSpans is not a function
        at buildMappingData (/home/mistergibson/Documents/Development/gxg-studio/node_modules/@babel/core/lib/transformation/file/merge-map.js:146:12)
        at mergeSourceMap (/home/mistergibson/Documents/Development/gxg-studio/node_modules/@babel/core/lib/transformation/file/merge-map.js:21:17)
        at generateCode (/home/mistergibson/Documents/Development/gxg-studio/node_modules/@babel/core/lib/transformation/file/generate.js:74:39)
        at run (/home/mistergibson/Documents/Development/gxg-studio/node_modules/@babel/core/lib/transformation/index.js:55:33)
        at run.next (<anonymous>)
        at Function.transform (/home/mistergibson/Documents/Development/gxg-studio/node_modules/@babel/core/lib/transform.js:27:41)
        at transform.next (<anonymous>)
        at step (/home/mistergibson/Documents/Development/gxg-studio/node_modules/gensync/index.js:254:32)
        at gen.next (/home/mistergibson/Documents/Development/gxg-studio/node_modules/gensync/index.js:266:13)
        at async.call.value (/home/mistergibson/Documents/Development/gxg-studio/node_modules/gensync/index.js:216:11)
     @ ./src/main/index.js 48:12-45
     @ multi ./src/main/index.js

**Expected/desired behavior:**
process the large javascript file and conclude.

* **What is the expected behavior?**
process the large javascript file and conclude.

* **What is the motivation / use case for changing the behavior?**
I need to compile my code? odd question.

**Comment by luoguoxiong** [comment]
I had a similar problem ~~~~~

**Comment by nicolo-ribaudo** [comment]
`merge-map.js` has been simplified, we don't use `computeColumnSpans` anymore: https://github.com/babel/babel/blob/main/packages/babel-core/src/transformation/file/merge-map.ts

**Comment by vasicvuk** [comment]
Hi @nicolo-ribaudo, Can you explain how should we use this version without calling computeColumnSpans. Latest version of npmjs is 7.18.10 and it still has this issue?
