### ISSUE TITLE
Bug: Regular expression syntax error

### ISSUE THREAD

**Issue by januwA** [babel/babel-loader#888]
**Webpack Version:**
5.11.1

**Babel Core Version**:
7.12.10

**Babel Loader Version**:
8.2.2

**Please tell us about your environment:**
Windows 10

**Current behavior:**
```
ERROR in ./src/index.ts
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: D:\ajanuw\webpack-scaffold\src\index.ts: Expected atom at position 67
    me>\w+)\s*{(?<props>
              ^
    at bail (D:\ajanuw\webpack-scaffold\node_modules\regjsparser\parser.js:1135:13)
    at parseTerm (D:\ajanuw\webpack-scaffold\node_modules\regjsparser\parser.js:486:9)
    at parseAlternative (D:\ajanuw\webpack-scaffold\node_modules\regjsparser\parser.js:457:21)
    at parseDisjunction (D:\ajanuw\webpack-scaffold\node_modules\regjsparser\parser.js:437:16)
    at parse (D:\ajanuw\webpack-scaffold\node_modules\regjsparser\parser.js:1150:18)
    at rewritePattern (D:\ajanuw\webpack-scaffold\node_modules\regexpu-core\rewrite-pattern.js:339:15)
    at PluginPass.RegExpLiteral (D:\ajanuw\webpack-scaffold\node_modules\@babel\helper-create-regexp-features-plugin\lib\index.js:94:49)
    at newFn (D:\ajanuw\webpack-scaffold\node_modules\@babel\core\node_modules\@babel\traverse\lib\visitors.js:175:21)
    at NodePath._call (D:\ajanuw\webpack-scaffold\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (D:\ajanuw\webpack-scaffold\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:42:17)

webpack 5.11.1 compiled with 1 error in 24331 ms
i ｢wdm｣: Failed to compile.
```

**Expected/desired behavior:**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
* 
```ts
const exp = /\s*(?<typedef>typedef)?\s*(?<struct>struct)\s*(?<structName>\w+)\s*{(?<props>[^}]*)}(\s*(?<aliasName1>\w+)?\s*,\s*(?<aliasName2>\*\w+)?\s*;\s*)?/gi;
console.log(exp);
```

* **What is the expected behavior?**
no error, no warning

* **What is the motivation / use case for changing the behavior?**
error and  warning

**Comment by januwA** [comment]
[REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=true&code_lz=GYVwdgxgLglg9mABANwBQEpEG8BQjEQIDOUiApgB4AOiAvIgPQA6RAVKgPwA8UAnlWQAmZYAD4-A4cHQcW7biQBOIaKKUqo6OZy7roAOQCGAWzKimAdwDUWtlh1VFcKkVEBtAHoBfALqt0Xqja3IYANjCGREamAIzm1jJyADTBXGERUSZkAEzmrJY2smwA3HIyDADmMMV4hGBEcKFkAHShcBWolFToNV44OGjoQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env%2Ces2017%2Ctypescript&prettier=true&targets=&version=7.10.4&externalPlugins=)

**Comment by nicolo-ribaudo** [comment]
Please report this to https://github.com/jviereck/regjsparser/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc, which is the parser that Babel uses internally for regular expressions :pray:
